### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by aptvaibhav** [mozilla/ichnaea#1072]
Can u please make the readme more elaborate?
So, that new contributor's can understand the project better.

**Comment by willkg** [comment]
Hi!

The readme points to our docs here: https://ichnaea.readthedocs.io/en/latest/

What kinds of things do you need to understand that you're not finding there?

**Comment by jwhitlock** [comment]
@aptvaibhav feel free to comment or reopen if you have suggestions for the documentation.
