### ISSUE TITLE
Wifi submission not working

### ISSUE THREAD

**Issue by ayanakshi** [mozilla/ichnaea#1166]
I an trying to add wifi data using geosubmit api but it is not getting into db for my location. I tried some location which were available in geoIp json file, it worked for those location. Is there any check with geoIp during wifi submissions? If it is, please help me where i can see it in code?

**Comment by jwhitlock** [comment]
Are you using https://location.services.mozilla.com/ or your own instance?

Submissions (see [/v2/geosubmit docs](https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html)) use a position obtained from a source such as GPS. I don't believe that geoIP is used as a reference during submission.

**Comment by ayanakshi** [comment]
I am using my local instance. If I submit wifi details with location of one of the country which is listed in geoip json then it works. When I use India, it doesn't add the wifi in mysql db.

**Comment by jwhitlock** [comment]
Can you add a submit JSON to this bug? Just one station if you can.

**Comment by ayanakshi** [comment]
The below request is working. It is from Germany I think
 curl -H 'Content-Type: application/json' http://127.0.0.1:8000/v2/geosubmit?key=test -d \
'{"items": [{"wifiAccessPoints": [{"macAddress": "94B40F010D01"}, {"macAddress": "94B40F010D00"}, {"macAddress": "94B40F010D03"}], "position": {"latitude": 51.0, "longitude": 10.0}}]}'

But this one is not working: 
curl -H 'Content-Type: application/json' http://127.0.0.1:8000/v2/geosubmit?key=test -d \
'{"items": [{"wifiAccessPoints": [{"macAddress": "94B40F010D01"}, {"macAddress": "94B40F010D00"}, {"macAddress": "94B40F010D03"}], "position": {"latitude": 13.0, "longitude": 78.0}}]}'

Only lat long change is here from above.  Even if I take different mac address that even doesn't work.

**Comment by jwhitlock** [comment]
I was able to get this to work. Here's what I did.

With `make mysql`, I got a MySQL shell, and reduced the batch size:

```
UPDATE export_config SET batch=1 WHERE name="internal";
```

The default is 100, which means you'll need 100 submissions for an API key to start processing them (or wait an hour). If you left the celery workers running, then they may have hit the 1 hour timeout and processed the stations.

I then ran the web service (`make run`) and the workers (`make runcelery` in another terminal)

After the first ``curl`` command (in a third terminal), and waiting a minute for processing, the stations are in the shard 0 table:

```
curl -H 'Content-Type: application/json' http://127.0.0.1:8000/v2/geosubmit?key=test -d '{"items": [{"wifiAccessPoints": [{"macAddress": "94B40F010D01"}, {"macAddress": "94B40F010D00"}, {"macAddress": "94B40F010D03"}], "position": {"latitude": 51.0, "longitude": 10.0}}]}'
```

```
mysql> SELECT hex(mac), lat, lon, region FROM wifi_shard_0;
+--------------+------+------+--------+
| hex(mac)     | lat  | lon  | region |
+--------------+------+------+--------+
| 94B40F010D00 |   51 |   10 | DE     |
| 94B40F010D01 |   51 |   10 | DE     |
| 94B40F010D03 |   51 |   10 | DE     |
+--------------+------+------+--------+
```

After the second command, the station is cleared:

```
curl -H 'Content-Type: application/json' http://127.0.0.1:8000/v2/geosubmit?key=test -d '{"items": [{"wifiAccessPoints": [{"macAddress": "94B40F010D01"}, {"macAddress": "94B40F010D00"}, {"macAddress": "94B40F010D03"}], "position": {"latitude": 13.0, "longitude": 78.0}}]}'
```

```
mysql> SELECT hex(mac), lat, lon, region FROM wifi_shard_0;
+--------------+------+------+--------+
| hex(mac)     | lat  | lon  | region |
+--------------+------+------+--------+
| 94B40F010D00 | NULL | NULL | DE     |
| 94B40F010D01 | NULL | NULL | DE     |
| 94B40F010D03 | NULL | NULL | DE     |
+--------------+------+------+--------+
3 rows in set (0.00 sec)
```

This is because the position moved so far that the WiFi stations have been moved to "blocked". This is used to detect mobile WiFi stations, like those on trains, or ones that have moved, such as an owner bringing the base station to a new house.

If I change the MAC address in the command, they are created as new stations (after waiting for processing):

```
curl -H 'Content-Type: application/json' http://127.0.0.1:8000/v2/geosubmit?key=test -d '{"items": [{"wifiAccessPoints": [{"macAddress": "95B40F010D01"}, {"macAddress": "95B40F010D00"}, {"macAddress": "95B40F010D03"}], "position": {"latitude": 13.0, "longitude": 78.0}}]}'
```

```
mysql> SELECT hex(mac), lat, lon, region FROM wifi_shard_0;
+--------------+------+------+--------+
| hex(mac)     | lat  | lon  | region |
+--------------+------+------+--------+
| 94B40F010D00 | NULL | NULL | DE     |
| 94B40F010D01 | NULL | NULL | DE     |
| 94B40F010D03 | NULL | NULL | DE     |
| 95B40F010D00 |   13 |   78 | IN     |
| 95B40F010D01 |   13 |   78 | IN     |
| 95B40F010D03 |   13 |   78 | IN     |
+--------------+------+------+--------+
6 rows in set (0.00 sec)
```

**Comment by ayanakshi** [comment]
Hii @jwhitlock , thankyou for ur response.  To process the batch, I was doing expire in redis as this was mentioned in doc.
I was able to make till second step when I changed lat long to a far place. But when I changed lat long to india location with different mac addresses, it was not going into DB. 
I will try with export config once.
I have taken the latest code from Git.
Could you please confirm that it is working on latest code and in local instance if possible?

**Comment by ayanakshi** [comment]
Hii @jwhitlock , thanks a lot, it worked for me also.. :)

**Comment by ayanakshi** [comment]
Hii @jwhitlock , could you please try this one: curl -H 'Content-Type: application/json' http://127.0.0.1:8000/v2/geosubmit?key=test -d '{"items": [{"wifiAccessPoints": [{"macAddress": "F6C4F3103D98","age": 5000,        "frequency": 2417,"signalStrength": -58},{"macAddress": "D05AA88530A5","age": 5000,"frequency": 2442,"signalStrength": -53},{"macAddress": "029B0A1DF768","age": 5000,      "frequency": 2417,"signalStrength": -24}],"position": {"latitude": 12.974620,"longitude": 70.672740,"accuracy": 27.0,"age": 5000,"altitude": 0 }}]}'


It is not working for me but changing lat long to 13.0 and 78.0 respectively is working.
