### ISSUE TITLE
Building on Raspberry Pi

### ISSUE THREAD

**Issue by AloyseTech** [mozilla/ichnaea#1262]
I'm trying to setup Ichnaea on a Raspberry Pi 4 (4GB). (Linux pi4 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux)
I'm not familiar with docker but I managed to change the base image to match the ARMv7 architecture. I also changed the installed package list to replace mysql by mariadb (I don't know if this will work though) and to install additional dependencies needed by some python requirements. The Dockerfile change : [patch_ichnaea_rpi.txt](https://github.com/mozilla/ichnaea/files/4890976/patch_ichnaea_rpi.txt)

When I'm running `make build`, after a long time (building gevent numpy and scipy takes a lot of time) the script fails at the `docker.make build_check` stage with the following error : 

> Step 24/27 : RUN make -f docker.make build_check
>  ---> Running in 4495cb155917
> /usr/local/bin/encode
> /usr/local/bin/enumerate
> /usr/local/bin/merge
> /usr/local/bin/render
> /usr/bin/pngquant
> /usr/local/bin/python -c "import sys; from shapely import speedups; sys.exit(not speedups.available)"
> make: *** [docker.make:80: build_check] Error 1
> ERROR: Service 'app' failed to build: The command '/bin/sh -c make -f docker.make build_check' returned a non-zero code: 2
> make: *** [Makefile:69: build] Error 1

I understand this might be an issue with the installation of shapely as a python requirement. I tried to install Shapely standalone on the system to check the speedups.available statement. If using `pip3 install shapely`, the statement return False. But if I do `pip3 install shapely --no-binary=shapely` the statement return True (which is what is expected from the script I guess). So I tried to add `--no-binary=shapely` at the end of the defaults.txt requirements file but it still does not work and the statement is not verified.

Also, if you know a way to avoid rebuilding wheels when installing the python dependencies indise the docker it would be great. Currently the `make build` process takes more than 1 hour before failing.

**Comment by jwhitlock** [comment]
I'm impressed, but doubt a Raspberry Pi will be a good platform for a full Ichnaea deployment. Our [deployment diagram](https://ichnaea.readthedocs.io/en/latest/_images/deploy.png) is a little out of date, but it gives an idea of the range of services from databases to caches to object storage needed for a full deployment.

I'll assume you know the limitations, and want to continue.

In `docker.make` you should comment out line 80, which checks that `shapely` was built with speedups. This is used to speedup the code path where a latitude and longitude is turned into a region, but the "slow" version should still work. You may want to remove other checks. In fact, I'd comment out the line ``RUN make -f docker.make build_check`` from ``Dockerfile``, and run it after everything else is built, to see what checks will fail without halting your build.

I don't think there is a way to avoid rebuilding the wheels. The `apt-get update` steps, needed to build the Python packages, will tend to change the filesystem, which will then invalidate later steps in the Dockerfile. I believe this is a limitation of how Docker works.

It may be possible to build the Docker image on a more capable computer, then transfer it to run on the Raspberry Pi. We build our Docker images in CircleCI, which takes about 3 minutes after Docker has downloaded base images.

**Comment by jwhitlock** [comment]
@AloyseTech, if you continue to have issues, feel free to comment or open a new issue. I don't think this project will officially support Raspberry Pi at this time, but this may be a good focus for a fork of the project.

**Comment by AloyseTech** [comment]
@jwhitlock Thanks for providing some guidance. I gave up the raspberry pi port for now but I might retry later this year.
