### ISSUE TITLE
RNC and SGSN Communication RANAP

### ISSUE THREAD

**Issue by denyl3l0** [mozilla/ichnaea#1263]
Hi All,

Im having trouble in my configuration, RANAP - InitialUE-Message [ GMM Service Request ] brings two different LAC(Location Area Code) in the parameters LAI(Location Area ID) and SAI(Service Area ID). Please see the trace below:
![LAI and SAC](https://user-images.githubusercontent.com/68634944/88148230-33d1c400-cbf6-11ea-8a3a-7b030eadc988.PNG)

can you help by saying the issue.

**Comment by jwhitlock** [comment]
@denyl3l0 I'm not familiar with the program that generated this screenshot, and I'm not familiar enough with cell data to guess what you are trying to do. Can you explain what you are trying to do with the cell data?

For MLS, cell data is used to call the geolocate API, and potentially other APIs:

https://ichnaea.readthedocs.io/en/latest/api/geolocate.html

Our APIs are designed to closely match the Google geolocation APIs:

https://developers.google.com/maps/documentation/geolocation/overview

If I had to guess, I think the Location Area is more precise than the Service Area, and so the code from the Location Area should be used with either service. You may be able to use a service like https://cellidfinder.com to confirm this.

**Comment by jwhitlock** [comment]
Feel free to reopen if you can provide more information.
