### ISSUE TITLE
Is the map updated at location.services.mozilla.com/map ?

### ISSUE THREAD

**Issue by deevroman** [mozilla/ichnaea#1321]
For several months in a row I made gps tracks, but they are still not on the map. I don't know if they are in the database, so first I want to know if the map is updated.

**Comment by jwhitlock** [comment]
No, this has not been running for about a year. The map update script has not been updated to work with the updated codebase yet. See https://github.com/mozilla/ichnaea/issues/840 for details.

**Comment by jwhitlock** [comment]
Closing in favor of #840
