### ISSUE TITLE
Redis Configuration

### ISSUE THREAD

**Issue by mugambi40** [mozilla/ichnaea#1373]
Here is a message am getting from Digital Ocean.

```
We’ve received a notification from an external nonprofit security organization, the Shadowserver Foundation, that your Droplet at IPAdress is running a Redis instance configured in a way that may be insecure.
This configuration may allow attackers to access your Redis instance and remove or modify the data hosted within it. This note is to inform you that your data might be at risk, based on their reporting.
```

**Comment by jwhitlock** [comment]
Thank you for filing an issue, @mugambi40. From what you've posted, this sounds like an issue with your Redis configuration with Digital Ocean, and not an Ichnaea issue. Do you have more information why it is an Ichnaea issue?

There may be more information in your message from Digital Ocean about steps to secure your Redis installation, or on this page:

https://www.digitalocean.com/docs/databases/redis/how-to/secure/

**Comment by jwhitlock** [comment]
Feel free to re-open if there is a change needed to Ichnaea or its docs.
