### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#1391]
Google Analytics appears to be blocked by CSP in Safari, with the error message:

```
Refused to connect to https://www.google-analytics.com/j/collect?dl=https%3A%2F%2Flocation.services.mozilla.com%2F&<omitted> because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.
```

Firefox Dev Edition doesn't appear to attempt the connection, and it is successful in Chrome.

The website is not an important part of the MLS service, and we don't need to measure web traffic with Google Analytics. We are measuring API usage though logs and metrics. The Google Analytics code should be removed.

*Originally filed as [bug 1642422](https://bugzilla.mozilla.org/show_bug.cgi?id=1642422) on 2020-06-01*

**Comment by arps18** [comment]
Hello @jwhitlock I would like to work on the issue!

**Comment by jwhitlock** [comment]
Thanks @arps18! Take a look and let me know if you have any questions.

**Comment by jwhitlock** [comment]
Removed from production
