### ISSUE TITLE
Remove celery_incoming queue

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#1408]
The ``celery_incoming`` queue is defined in the task app as a celery task queue:

https://github.com/mozilla/ichnaea/blob/db9bb33800fdeb9d0cced1ede41b9fa2d673d353/ichnaea/taskapp/config.py#L20

However, no tasks are assigned to it. Stop creating it, and remove it from the metrics doc.

**Comment by rajreet** [comment]
Can I work on this?

**Comment by jwhitlock** [comment]
Yes @rajreet! Take a look and let me know if you have any questions.

**Comment by rajreet** [comment]
I was following these steps under Setup Quickstart:
[Docs](https://ichnaea.readthedocs.io/en/latest/local_dev.html)

And I got stuck in step 4. Here is the error:
![Screenshot from 2020-11-05 10-47-05](https://user-images.githubusercontent.com/32609376/98201013-d10df980-1f54-11eb-98c9-acd02232629b.png)

@jwhitlock I have changed the UID/GID as mentioned. I am new to Docker, can you please tell me why is it giving error. Any learning materials about docker would be helpful too.
