### ISSUE TITLE
Replace pytz.UTC with zoneinfo('UTC')

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#1440]
We're using ``pytz.UTC`` for timezone-aware dates. Python 3.9 has added [zoneinfo](https://docs.python.org/3.9/library/zoneinfo.html) as a standard module. If we use this, then ``pytz`` can be removed from first-level requirements.

Old code:

```
from pytz import UTC

def utcnow():
    """Return the current time in UTC with a UTC timezone set."""
    return datetime.utcnow().replace(microsecond=0, tzinfo=UTC)
```

New code:

```
from zoneinfo import ZoneInfo

def utcnow():
    """Return the current time in UTC with a UTC timezone set."""
    return datetime.utcnow().replace(microsecond=0, tzinfo=ZoneInfo("UTC"))
```

The timezone-aware ``datetime`` objects created with ``pytz.UTC`` are equivalent to the ones created with ``ZoneInfo("UTC")`` - see https://gist.github.com/jwhitlock/08ca74b037c2196f946262ef1a4b775d

**Comment by dantesCode** [comment]
I want to make this issue :)

**Comment by jwhitlock** [comment]
This was complete after #1462 and #1464, and should have been closed in December 2020. Thanks for your help @dantesCode!
