### ISSUE TITLE
Range too large in OpenCellID data

### ISSUE THREAD

**Issue by greenwoodpt** [mozilla/ichnaea#1443]
Hello I'm newbie here! I've just downloaded the OpenCellID data and checked the Range (measured in meters of the area where the cell can be, source: http://wiki.opencellid.org/wiki/Menu_map_view#database). The range has too large values (e.g. 700-1000km for UMTS and 70km for GSM). Do you think this is valid? Thanks!

**Comment by jwhitlock** [comment]
If you downloaded the data from http://opencellid.org/downloads, then you should ask about this on the OpenCellID forums, see https://community.opencellid.org.

If you downloaded the data from https://location.services.mozilla.com, there are known problems with cell data (such as https://github.com/mozilla/ichnaea/issues/486), I wouldn't be surprised if there are some incorrectly large cells as well. At the same time, large values may be correct. The [accuracy documentation](https://ichnaea.readthedocs.io/en/latest/algo/accuracy.html) says there are GSM cells as large as 120 km. 1000km seems too far for a cell tower, but I don't have a lot of experience with cell tech.

**Comment by greenwoodpt** [comment]
Thank you very much! I'll check the sources and information you mentioned. Have a good weekend!
