### ISSUE TITLE
mobile-codes: Standardize data mapping

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#1446]
The mapping between strings in different data sets is done in code with some search and replace. This is not fully tested, and may break with future imports. Use a string mapping technique that makes it clearer what conversions are being made, to ease future imports.

**Comment by Alonmask** [comment]
No tracking system audit update

**Comment by Alonmask** [comment]
@jwhitlock

**Comment by Alonmask** [comment]
![Uploading IMG20211129115859-01.jpeg…]()

**Comment by Alonmask** [comment]
``

> @jwhitlock

DUydus
