### ISSUE TITLE
Move privacy notice to www.mozilla.org

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#1558]
Move the MLS privacy notice to https://www.mozilla.org/en-US/privacy/mozilla-location-service, so that it appears in the left toolbar at https://www.mozilla.org/en-US/privacy/. Change the links on the MLS website to point to the new location, and redirect as needed.

**Comment by jwhitlock** [comment]
The privacy notice has been merged. Once it is published at https://www.mozilla.org/en-US/privacy/, we can remove it from this repo and redirect links to www.mozilla.org.

**Comment by jwhitlock** [comment]
Publishing will require some changes:

It needs to be added to the `navigation_bar`:

* https://github.com/mozilla/bedrock/blob/7612841682eaf1af5e61aec621407b2887d03938/bedrock/privacy/templates/privacy/base-protocol.html#L29-L42

It needs to be added to the URLs and views:

* https://github.com/mozilla/bedrock/blob/master/bedrock/privacy/urls.py
* https://github.com/mozilla/bedrock/blob/master/bedrock/privacy/views.py

It will need to be added to the FTL file:

* https://github.com/mozilla/bedrock/blob/master/l10n/en/privacy/index.ftl

**Comment by Jayboy41ok** [comment]
![Screenshot_20230719-122918](https://github.com/mozilla/ichnaea/assets/139551199/86916577-20f9-43ba-a821-617fc847b663)

**Comment by Jayboy41ok** [comment]
You guys. Who added these additional codes to my network? I'm not trying to do anything other than get assistance referencing chrome/play store. See attached the large amount of data used by theses apps. This is causing my text messages delay. CCT running to fast

**Comment by Jayboy41ok** [comment]
![Screenshot_20230719-135444](https://github.com/mozilla/ichnaea/assets/139551199/13c5e75c-a939-47e5-a241-3e0fe514af19)
