### ISSUE TITLE
Consider dropping potentially unused indexes

### ISSUE THREAD

**Issue by cvalaas** [mozilla/ichnaea#1622]
Regarding the `wifi_shard_*` tables, consider dropping potentially unused indexes on these fields:

- `created`
- `modified`
- `lat` & `lon` (combined index)
- `region`

I don't know for sure that these indexes aren't used (and if they are being used somewhere they should stay!), but all the queries I've seen have only used the PRIMARY (`mac`) index.
A lot of queries on the replica look at `mac` and `lat`/`lon` in the WHERE clause, but an explain shows that only the PRIMARY index is being used.

If this seems like a good idea, we should also figure out what kind of an effect on the service altering these tables would have...

**Comment by jwhitlock** [comment]
A significant amount of space is taken up by these indexes, so if they are unneeded it would help us stay within our DB resources to remove them. I suspect these indexes were added for periodic tasks, such as counting stations by region. That doesn't guarantee that they are used.

I think the first step is to gather the SQL used by periodic tasks. It is not clear to me how to do that.

**Comment by cvalaas** [comment]
Ah yes, the wifi SQL (seen in https://github.com/mozilla/ichnaea/issues/1620) definitely *does* use the `region` index. So that should stay.
I can't find anywhere that uses the `created` or `modified` indexes for the wifi or blue shard tables.
The `datamap` and `stat` tables **do** use date indexes when deleting old records.
Looks like the [write_to_csv](https://github.com/mozilla/ichnaea/blob/32c757733c6edddb081346025ea6f64a86cfe12f/ichnaea/data/public.py#L42) method could use those indexes. But I couldn't see it running. Is it disabled?

'twould be nice if there were some mysql statistic to track index usage, but if there is, I can't find it.
