### ISSUE TITLE
Differentiate between 2 and 3 digit MNCs in the API

### ISSUE THREAD

**Issue by tpikonen** [mozilla/ichnaea#1707]
The "mobileNetworkCode" field in the APIs is defined as an integer. This results in loss of information, since two and three digit MNC are considered different (e.g. "01" != "001"). See the Wikipedia [Mobile country code article](https://en.wikipedia.org/wiki/Mobile_country_code) for reference.

A new "operatorCode" field concatenating "mobileCountryCode" and "mobileNetworkCode" into a single string could be added to the APIs without breaking backwards compatibility. This is how [ModemManager](https://www.freedesktop.org/software/ModemManager/libmm-glib/libmm-glib/MMLocation3gpp.html#mm-location-3gpp-get-operator-code) in the Linux location stack does it now.

**Comment by jwhitlock** [comment]
Sorry for the long wait for a response!

Looking at [Mobile country code](https://en.wikipedia.org/wiki/Mobile_country_code#Test_networks), it appears these are used for test networks:

MCC | MNC | Brand | Operator | Status | Bands (MHz) | References and notes
-- | -- | -- | -- | -- | -- | --
001 | 01 | TEST | Test network | Operational | any |  
001 | 001 | TEST | Test network | Operational | any |  

I'm not sure if we're losing much information by not distinguishing between the two test networks, so this seems like a low-priority issue.

The operatorCode sounds interesting. It would be a new API version, but could be applied as optional fields without a version bump.
