### ISSUE TITLE
Unable to use Google as a fallback

### ISSUE THREAD

**Issue by JayTheLegend** [mozilla/ichnaea#1739]
I'm trying to setup google as a fallback if Ichnaea am unable to get the location. I have 2 questions

1. Would Ichnaea use the location received from google and submit the result to build it's own the database?
2. I can invoke the Google API directly via postman but when Ichnaea tries to do same it returns "code": 404,"message": "Not found". Looking at the metrics on google, I am hitting the service. I'm wondering if I added the correct information to the api_key table and if the JSON format sent through is correct. Please have a look and see if I'm missing something: 

INSERT INTO api_key (valid_key, maxreq, allow_fallback, allow_locate, allow_region, fallback_name, fallback_schema, fallback_url, fallback_ratelimit, fallback_ratelimit_interval, fallback_cache_expire, store_sample_locate, store_Sample_submit)
VALUES ('MyKey', '10000', '1', '1', '1', 'Google_Fallback', 'googlemaps/v1', 'https://www.googleapis.com/geolocation/v1/geolocate?key=MyKey', '10', '60', '86400', '100', '100'); 

It does work when only using Cell towers, but presumably that is because I have imported them from a csv file so its not querying google. The moment I give it WiFi MAC addresses I get the said result.

**Comment by jwhitlock** [comment]
I haven't used the fallback configuration myself, but those values look correct to me.

Are you sending one WiFi MAC address or multiple? The queries fail with a single WiFi:

https://ichnaea.readthedocs.io/en/latest/api/geolocate.html#field-definition

> All of the fields are optional, but in order to get a Bluetooth or WiFi based position estimate at least two networks need to be provided and include a `macAddress`. The two networks minimum is a mandatory privacy restriction for Bluetooth and WiFi based location services.

If you are using multiple WiFi MAC addresses, you may need to bootstrap with some data before it will use the fallback.

**Comment by JayTheLegend** [comment]
@jwhitlock  Thanks for the response.

I am indeed sending multiple MAC addresses, tried as much as 5. I used an app on my phone to check the WiFi networks around me (Gives plenty of information).

I can't remember how many combinations of Information I tried when posting, I'll play around with some values, but with the Google API you can get away with only Signal strength and MAC. I'd imagine that these parameters would be passed at the very least?

**Comment by jwhitlock** [comment]
I haven't tried the Google fallback myself, so I'm guessing at this point. You may want to add logging and print statements to try to determine what the code is doing with your data.

You may also be interested in the GeoLite2 database, which will at least give you some data based on your (external) IP address:

https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en

**Comment by JayTheLegend** [comment]
@jwhitlock Thanks for the response.

I had to make a plan and wrote a peace of middle ware to resolve this issue for the time being. I will revisit this when I need it for a live environment and do a proper debug and post my findings.

If anyone come across this issue, please let me know. Thanks!
