### ISSUE TITLE
Sorting out inactive users (leaderboard cleanup)

### ISSUE THREAD

**Issue by Djfe** [mozilla/ichnaea#187]
Should we sort out users from our leaderboard with less than 1 entry?
This would clean up the leaderboard.

We could wait until one week after their first upload  and then hide or delete them.

Hiding might be even better, we could show them again on the leaderboard if they upload again.

**Comment by hannosch** [comment]
This issue is going to be made obsolete by the new standalone leaderboard service (#456).
