### ISSUE TITLE
Tables datamap_* are empty

### ISSUE THREAD

**Issue by Alixpat** [mozilla/ichnaea#1910]
Hi,
I'd like to build datamap.
However, tables datamap_* are empty whereas there is lot of data in database (wifi, cell).
Should I run some process ?
Regards.

**Comment by jwhitlock** [comment]
The `datamap` tables are updated by the `DatamapUpdater` background task:

https://github.com/mozilla/ichnaea/blob/eceb1218ef7cbfe639b67cdc89ce422b14ee83f3/ichnaea/data/datamap.py#L31

To run the background tasks, you'll need to run both a task worker and the scheduler. See the development environment instructions to get started:

https://ichnaea.readthedocs.io/en/latest/local_dev.html#running-tasks

However, these tasks process incoming data, and I suspect you injected data from another source. Look at the source code for `DatamapUpdater` for clues on how to populate the tables from existing data.

**Comment by Alixpat** [comment]
Hi,
Thank you for your reply.
All data come from geosubmit...
When I run :

**Comment by jwhitlock** [comment]
Try:

```sh
docker exec -it worker celery -A ichnaea.taskapp.app:celery_app call ichnaea.data.tasks.update_datamap --kwargs '{"shard_id": "sw"}'
```

The shards are:

* `"sw"` - southwest (South America?)
* `"nw"` - northwest (North America?)
* `"ne"` - northeast (Europe / Asia?)
* `"se"` - southeast (India / Australia?)

**Comment by Alixpat** [comment]
Hi,
It work's great, thanks you.
Shoud I run a cron script to run this process or it should normaly autorun ?
Regards

**Comment by jwhitlock** [comment]
For periodic tasks, we use `celerybeat`:

https://github.com/mozilla/ichnaea/blob/eceb1218ef7cbfe639b67cdc89ce422b14ee83f3/docker/run_scheduler.sh#L3-L5

Here's how we run it in `docker-compose.yml`:

https://github.com/mozilla/ichnaea/blob/eceb1218ef7cbfe639b67cdc89ce422b14ee83f3/docker-compose.yml#L28-L37

This is roughly comparable to:

```sh
docker run mozilla/location scheduler
```
except you'll need environment variables, etc. to match your deployment.

Each repetitive task defines a `_schedule` and other parameters:

https://github.com/mozilla/ichnaea/blob/eceb1218ef7cbfe639b67cdc89ce422b14ee83f3/ichnaea/data/tasks.py#L169-L180

The `celerybeat` task uses these parameters to add a task to the task queue (a Redis [list](https://redis.io/docs/data-types/lists/)), which is then picked up by the `celery` workers. We run a single worker in the development environment, and several workers in production. See the [deployment docs](https://ichnaea.readthedocs.io/en/latest/deploy.html) for an overview.

**Comment by Alixpat** [comment]
Hi,
Yes, I've already a scheduler container running.
However, I should run task manually to update datamap_*  and region_stat table....
Regards.

**Comment by jwhitlock** [comment]
Manually running a task shouldn't be necessary, as long as 1) the scheduler is running and 2) you have a worker processing the queue.

You may need to confirm your scheduler is running. If it detects the PID file, it exits on startup:

```
scheduler_1  | Starting Celery Scheduler
scheduler_1  | celery beat v5.2.7 (dawn-chorus) is starting.
scheduler_1  | ERROR: Pidfile (/var/run/location/celerybeat.pid) already exists.
scheduler_1  | Seems we're already running? (pid: 8)
ichnaea_scheduler_1 exited with code 73
```

You may want to check that you have a worker pulling jobs from the `celery_content` queue. For example, when I launch a worker, it lists the `celery_content` queue:

```
worker_1     |  -------------- celery@860a415c1fd2 v5.2.7 (dawn-chorus)
worker_1     | --- ***** ----- 
worker_1     | -- ******* ---- Linux-5.10.104-linuxkit-aarch64-with-glibc2.31 2022-10-10 15:03:18
worker_1     | - *** --- * --- 
worker_1     | - ** ---------- [config]
worker_1     | - ** ---------- .> app:         ichnaea.taskapp.app:0xffff95582680
worker_1     | - ** ---------- .> transport:   redis://redis:6379/0
worker_1     | - ** ---------- .> results:     redis://redis:6379/0
worker_1     | - *** --- * --- .> concurrency: 2 (prefork)
worker_1     | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker_1     | --- ***** ----- 
worker_1     |  -------------- [queues]
worker_1     |                 .> celery_blue      exchange=celery_default(direct) key=celery_blue
worker_1     |                 .> celery_cell      exchange=celery_default(direct) key=celery_cell
worker_1     |                 .> celery_content   exchange=celery_default(direct) key=celery_content
worker_1     |                 .> celery_default   exchange=celery_default(direct) key=celery_default
worker_1     |                 .> celery_export    exchange=celery_default(direct) key=celery_export
worker_1     |                 .> celery_monitor   exchange=celery_default(direct) key=celery_monitor
worker_1     |                 .> celery_reports   exchange=celery_default(direct) key=celery_reports
worker_1     |                 .> celery_wifi      exchange=celery_default(direct) key=celery_wifi
```

If you do not have a working consuming that queue, then the scheduler is publishing to nothing.

**Comment by jwhitlock** [comment]
@Alixpat I'm closing as fixed, please re-open or open a new issue if you have further questions.
