### ISSUE TITLE
Determine a data retention policy for Measurement data we archive to S3

### ISSUE THREAD

**Issue by crankycoder** [mozilla/ichnaea#192]
We certainly don't need to keep the data forever in S3.  I doubt we need to keep the WifiMeasure data longer than 6 months.

#188 is going to file data into S3 using keys with YYYYMM/filename format so we can easily go back and delete data.

For CellMeasurements - we may want to keep the data much longer though.

Thoughts?

**Comment by hannosch** [comment]
The real code change to fix this is part of our S3 lifecycle setup, which happens outside this code base.

We'll use a one year retention period, to retain enough old data to rerun analysis, but make sure we don't hold onto raw data forever.
