### ISSUE TITLE
Time to update MLS database

### ISSUE THREAD

**Issue by carlocastoldi** [mozilla/ichnaea#1926]
Since [Mozilla Stumbler](https://github.com/mozilla/MozStumbler) was discontinued the data of MLS are getting older and older. Over at [geoclue](https://gitlab.freedesktop.org/geoclue/geoclue), Freedesktop geoinformation service widely used on Linux, we are trying to find an alternative solution in order to contribute to MLS. I was thus wondering how long does it usually take for MLS to report the updated location after they were submitted.

**Comment by jwhitlock** [comment]
The service continually processes updates in batches. I'd estimate 5 to 120 minutes for a submission to update the database. Not all submissions are treated equally. For example, a WiFi station seen in a location query can update that a WiFi station is still active, but won't change the location estimate. A submission report with a GPS or other location source is needed to update the location estimate. See https://ichnaea.readthedocs.io/en/latest/algo/observations.html for details.

The [datamap](https://location.services.mozilla.com/map#0.7/0/0) on the website is updated nightly, so it may take 24 hours for new submissions to appear.

It would be awesome if Geoclue added an interface to the MLS submission API, and Geoclue clients implemented "fix my location" user interfaces. That way, Geoclue users could contribute fixes directly.
