### ISSUE TITLE
`/v2/geosubmit` and other submission docs should say that API key is optional

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#1927]
The [services API doc](https://ichnaea.readthedocs.io/en/latest/api/index.html#api-access-keys) says:

> You can anonymously submit data to the service without an API key via any of the submission APIs.

The [/v2/geosubmit doc](https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html) says:

> Geosubmit requests are submitted using an HTTP POST request to the URL:
>
> `https://location.services.mozilla.com/v2/geosubmit?key=<API_KEY>`

It should mention that the `?key` parameter is optional. This would help MLS users that are attempting to make small scale fixes to the MLS database, as suggested in this [discourse thread](https://discourse.mozilla.org/t/api-key-request-for-updating-wifi-network-location/106165/3]).

**Comment by tyagi-data-wizard** [comment]
Hi @jwhitlock ,
I am new to open source and would like to contribute.
Created a [PR](https://github.com/mozilla/ichnaea/pull/1943) please have a look at the proposed changes and let me know if any change is needed.
Thanks!
