### ISSUE TITLE
colorize the coverage map based on the data's age

### ISSUE THREAD

**Issue by Djfe** [mozilla/ichnaea#198]
@grrrrr brought up the idea to mark new data on the coverage map differently
see Mozilla/Mozstumbler#579

This would help showing stumblers where data was collected last.

I'm not too sure how far this is doable, but I know that we would need to use the upload date instead of the recording date because the recording date is cut off to be monthly.

Is this doable? I'm not sure because the coverage map is fuzzy.

Maybe we should show this in the app (Mozstumbler) instead by enhancing the internal map's capabilites and the internal database.

@VolMi had the idea to mark 5+ years old entries instead, probably to be able to show the reliableness of the available data and indicate that the data should be updated again. (Maybe 1+ years is even more idealy)

Different map layers might show it even better. (so that you are able to switch between old and new data)

**Comment by hannosch** [comment]
This got duplicated by #466.
