### ISSUE TITLE
Can you please tell me where to follow-up referencing these codes

### ISSUE THREAD

**Issue by ghost** [mozilla/ichnaea#1998]
I was having lots of device problems, and reached out to chrome numerous times attempting to solve problems. Chrome was accumulating over 250gb of data. Now I'm seeing these codes attached to my network. Please advise me where or who can assist 
![Screenshot_20230719-122918](https://github.com/mozilla/ichnaea/assets/139551199/6fded50d-96a4-45bf-af2f-7e730e1a9537)

**Comment by jwhitlock** [comment]
Sorry, this does not sound like an issue with this project.
