### ISSUE TITLE
Save the Database

### ISSUE THREAD

**Issue by mrx23dot** [mozilla/ichnaea#2066]
Please consider donating the database to Wigle.net

they (and thus everyone) could greatly benefit from new datapoints.
Even if it's _anonymized_, containing just  **BSSID, RSSI, and location.** (no SSID)
(their website already contains what APs are at specific location, it's public knowledge)

Wigle.net has a nice averaging method, so worst case datapoint will be voted down because it's out of date,
but the possible upside is that you have datapoints in uncovered areas.

Don't let your hard work go to waste.

I attached a minimal working csv they accept:
[wiggle_slim.csv](https://github.com/mozilla/ichnaea/files/14877133/wiggle_slim.csv)

**Comment by alexcottner** [comment]
Unfortunately we cannot provide an export of the full data. The combination of a MAC address and a location is considered personal data in some jurisdictions, as this may contain data about the owner of the network. We are able to provide a cell data export and have created a final full export, located [here](https://d2koia3g127518.cloudfront.net/final_export/MLS-full-cell-export-final.csv.gz).
