### ISSUE TITLE
Add daily/weekly statistic about the requests for geolocation

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#234]
It would be interesting how many requests would be done per day/week.
Add a daily/weekly statistic about the requests for geolocation
- Result of daily/weekly requests (Number of requests)
- Result of successful or not successful requests  (Value in percent)

**Comment by hannosch** [comment]
The amount of technical work that this would require isn't worth it, considering these metrics would only be there to satisfy some curiosity.

The service has passed the 100 requests per second / 10 million requests per day mark a good while ago and continues to grow. Which really just means: this is a serious service and not a prototype anymore.
