### ISSUE TITLE
Web frontend to search cellid and show in map

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#244]
A interesting feature is to add a web frontend where you can enter mcc, mnc, lac and cellid and get the location in a map with latitude, longitude and the accuracy as circle.
Many people use gps tracker for her car, classic car, .. with use the cell id (and gps) to get the location if the car is stolen.

Example:
www.open-electronics.org/celltrack/
opencellid.org

**Comment by hannosch** [comment]
The website hasn't seen and won't see much attention. Visualizing the cell networks is something we'll leave to community projects.
