### ISSUE TITLE
Use radio network controller as fallback (UMTS)

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#286]
If we wont have entries for the actual cellid we could use the value rnc (radio network controller) as option.
It is different from provider to provider but it make sense if the location area code has more than one rnc or one rnc is used in two location area codes.

Example:
1. Location Area Code has one RNC (LAC = RNC, no advantage, same coverage)
2. Location Area Code has more as one RNC (3 RNC in one LAC, RNC range is better and smaller as location area code)
3. RNC is used in two different LAC (RNC 30 is used in LAC 43232 and 43231, RNC range could be better)

Is it possible to generate a statistic for the UMTS provider to check the three cases and make it sense to do this?

**Comment by Libya1980** [comment]
Hello ..
Nice to find like this converation .i have a question 
Is it normal to use one LAC id twice in different rnc in for one 3G MSC ??? 
In our network we have such this case since 2 month and in the same period we face problem in intra ho success rate % ?
