### ISSUE TITLE
Get better accuracy (range) when mobile phone supports neighboring cells

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#288]
My mobile phone supports neighboring cells.
In GSM mode i see as maximum 6 cells (with valid LAC, Cellid and signal strength) and the serving cell.
In UMTS mode the data are maybe not very useable (only psc).
Now the question: Could the accuracy (value range) be better if you have more than one cell?
With 2-6 existing neighboring cells the position could be better calculated as with one cell and give a better value range.
Maybe the static value range at the moment could get a better value when use more than one cell (and send them logically to MLS).

**Comment by hannosch** [comment]
For cell networks, we almost never get complete enough information from neighboring cell networks. Practically this only works in LTE networks. But in those networks the cell radii are already smaller, so the returned accuracy is also already better.

**Comment by hannosch** [comment]
Closing this issue, as it was originally about improving the accuracy estimates we return when we have data from multiple cells. We improved this in mid-January for cell and wifi networks. Our returned accuracy numbers are much lower these days and are based on all cells.
