### ISSUE TITLE
Add validation of GSM / UMTS cell ids ranges

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#304]
We currently have some GSM cells with cell ids larger than 64k and some UMTS cells with cell ids lower than 64k.

In both of these cases the radio type is likely wrong. Many older Android chipsets don't properly distinguish between GSM/UMTS and so we end up getting the wrong type.

We should normalize the radio type based on the cell id value. This applies both to the submission data as well as the search interface and needs a migration of existing cells.

**Comment by jas19** [comment]
How can we check the missing cell_id counts while migrating the data from one source to another ?
I am getting 10000 events on the target one but the actual records should be 30000.
How to check this ?
