### ISSUE TITLE
Calculated cell area has a too big range (radius)

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#309]
There are some cellids with a big cell area (range). Here is a example with a range from 61006.
UMTS,202,5,6022,2751509,,23.7591917437,37.9621134371,61006,437,1,1404243842,1409772033,

Maybe there exists a mysterious phenomenon why the range is here very big?

**Comment by hannosch** [comment]
This definitely still happens. We have a good number of cell networks with radii in the multiple thousand kilometer range.

**Comment by E3V3A** [comment]
Hmm, can you provide more info on those "networks"? It should be fairly straightforward to find out how this come about. And most importantly, what devices produce these measurements.

**Comment by timofonic** [comment]
Any news? I need geolocation and I'm worried about this...

**Comment by hannosch** [comment]
I haven't looked into this in a while. There are some cell areas which are indeed large, as they for example cross mainland US and Puerto Rico. I'm hoping to take another look at this later in the quarter, but more likely early next year.

**Comment by hannosch** [comment]
I've looked over the most extreme cases and manually dealt with those. For any new observations we do correctly handle the case where the cell radius would grow over our maximum radius limit. So at this point there shouldn't be any cells in the database with a radius of more than 150km - starting with tomorrows full cell export.

**Comment by Nikolche84** [comment]
So the maximum range at:

GSM is 35 km away
UMTS has no limit
LTE 200km


Is this true?
