### ISSUE TITLE
Cell ids with 0 samples and calculated range

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#310]
The file MLS-full-cell-export-2014-09-04T000000.csv include 273 cells with 0 samples but it exists a calculated range.

Examples:

GSM,208,1,1538,1072,,-1.0126809,44.6204882,9639,0,1,1383152241,1408453593,
GSM,208,1,1538,11137,,-0.9812667,44.6461851,37555,0,1,1383152241,1408453593,
GSM,208,1,1538,32721,,-1.0020882,44.6345924,35944,0,1,1383152481,1408453593,
GSM,208,1,1538,35428,,-1.0172121,44.6283811,9715,0,1,1383152481,1408453593,
GSM,250,7,17000,110,,47.263276,56.1281978,10425,0,1,1383146336,1408453593,
GSM,250,7,17000,130,,47.2537378,56.1300196,5998,0,1,1383210402,1408453593,
GSM,250,7,17000,1131,,47.2686209,56.1297081,10371,0,1,1383167298,1408453593,
GSM,250,7,17000,1430,,47.2631252,56.1327893,10029,0,1,1383113264,1408453593,
GSM,250,7,17000,1440,,47.261217,56.1369019,5083,0,1,1383144688,1408453593,
GSM,250,7,17000,1510,,47.2348469,56.1422686,5878,0,1,1383303975,1408453593,
GSM,250,7,17000,1520,,47.2326344,56.1371906,3649,0,1,1383124305,1408453593,
GSM,250,7,17000,1930,,47.2379978,56.1403619,5263,0,1,1383116094,1408453593,
GSM,250,7,17000,3021,,47.2599806,56.1312346,10146,0,1,1383167298,1408453593,
UMTS,262,7,21634,48106763,,13.7644184,51.0676573,3803,0,1,1386229776,1408453604,
LTE,311,5,21,17139,,-89.4026118,43.0242141,13488,0,1,1386287043,1408453604,
GSM,208,1,1538,57736,,-0.9336136,44.6369615,35693,0,1,1386364495,1408453604,
GSM,208,1,1538,48215,,-0.9694472,44.6313394,7303,0,1,1386364495,1408453604,

**Comment by hannosch** [comment]
I looked at this and manually set the total_measures to 1 where it was 0 or null.

We lost some data here while abusing the field for two different purposes. The last of those cells had been modified in 2014, so the bug was fixed a while ago. Not much else we can do about this.
