### ISSUE TITLE
Cells in MLS statistics and export file are different

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#311]
I have a question to the difference between the stats (https://location.services.mozilla.com/stats) and the export file (https://location.services.mozilla.com/downloads).

In the stats from the date 13.09.2014 there are 1811966 unique cells but the MLS-full-cell-export-2014-09-14T000000.csv a day later includes only 1773776 cells.

**Comment by hannosch** [comment]
After my last commit, the next major problem should be taken care of. Cells/Wifis which where previously blacklisted won't get double counted.

This does leave cell/wifi entries which get permanently blacklisted. In those cases we should likely just decrement the stats for the current day.

**Comment by hannosch** [comment]
I've manually adjusted the cell stats once more (after CDMA networks got removed) and the stats should be good now.
