### ISSUE TITLE
Add an API to support querying of leaderboard statistics 

### ISSUE THREAD

**Issue by crankycoder** [mozilla/ichnaea#313]
This is a short term stop gap measure to help support #312 until we have full FxA and Galaxy leaderboard integration working.

We want to be able to provide basic metrics to Mozilla Reps during the Stumbling in a Box parties.

Metrics should be scoped to a single mozilla rep.  

It's sufficient for now to be able to provide the same metrics we have on the weekly leaderboard.
  * new wifi's stumbled
  * new cell towers stumbled

cc/ @garvankeeley

**Comment by hannosch** [comment]
Moved to new project.
