### ISSUE TITLE
Add layer in map for data from OCID and MLS

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#320]
It would be interesting to see in the map the data from MLS and OCID as a separate layer.
Layer 1: Show only data from MLS in map
Layer 2: Show only data from OCID in map
Layer 3: Show data from MLS+OCID in map

**Comment by hannosch** [comment]
Realistically this won't happen. The OCID project has various maps to show their data and we have our one map to show our own. If someone wants to do a mashup of the two, that can be a separate project, but we won't get this done as part of ichnaea. ichnaea will rather focus on better ways to show our own data.
