### ISSUE TITLE
Change single letter variable names to meaningful names

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#346]
There are many places in the code which use single letter variables (d for a dictionary of data, w for a wifi signal, etc).  Use meaningful names rather than single letters.

**Comment by hannosch** [comment]
I consider this one done, to the point where it no longer needs a separate ticket. If we touch/rewrite code we can choose different names.

There are some places left that are mathematical formula taken from the outside, like the clustering or haversine formula. As those often use nameless/meaningless one letter variables for intermediate results in their canonical form, I'd leave those as-is as well.
