### ISSUE TITLE
Recreate the test database during each test run

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#347]
The `make test` command reuses the same test database during each test run, however this can miss schema changes or possibly bleed data.  It doesn't take long to instantiate a new database.  Should we possibly recreate it each time, or add an optional flag or environment variable to allow it to be recreated?

**Comment by hannosch** [comment]
@jaredkerim did this happen again at some point? Or can we close this?

**Comment by hannosch** [comment]
Considering this closed.
