### ISSUE TITLE
Provide a public API key that people can play with

### ISSUE THREAD

**Issue by crankycoder** [mozilla/ichnaea#359]
I've been hearing feedback from quite a few people that we really need to have a public API that is either API-key free for querying, or at least a known test API key that is severely rate limited so that people can play with real data.

"the incongruency of data in vs. data out is too much" was the complaint - and I'm inclined to agree.  You shouldn't have to have a provisioned API key just to play with the API. cc @mostrovsky

**Comment by hannosch** [comment]
Actually my idea in https://github.com/mozilla/ichnaea/issues/359#issuecomment-66272514 was way too complicated. We do have the public "test" key now and it's actually good enough so far.

For data submission you can just not send an api key. Using test for submission will internally discard all the data send in that way, as it's used to trigger a test mode.
