### ISSUE TITLE
Create geojson API for cell data

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#363]
We want to show cell locations in the stumbler app, with metadata about each cell network, like it's radio/mcc/mnc/lac/cid numbers but also the range value.

Current idea is to create expose this data as geojson, with a feature collection of points. The dataset is too large to expose it as one big geojson file, so we need to have some way to break it up. One way would be to use the typical map tiling approach of z/y/x files. We also want to allow someone to just query the data for a specific radio type, country code and operator, so one could for example only show the data for the currently active data connection (as that's the only one data is collected for in the app).

If we want to show this as a secondary layer on the website, https://github.com/glenrobertson/leaflet-tilelayer-geojson might be helpful.

A url scheme might look like this: ``/v1/cell/13/2288/2989.geojson``

The radio/mcc/mnc restriction could be done either as additional url path segments or via query strings. We'd also want to allow multiple values for some of them, so maybe either:

``/v1/cell/gsm,umts,lte/310,311/3/13/2288/2989.geojson`` or ``/v1/cell/13/2288/2989.geojson?radio=gsm,umts,lte&mcc=310,311&mnc=3``

It should be possible to specify just some of the restrictions, so for example just limit to radio type or just radio type / country restrictions. Since these are optional filters, I'm leaning towards using query strings for these.

The response for each tile would be something like:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "range": 1000,
        "mcc": 310,
        "mnc": 3,
        "lac": 1234,
        "cid": 23456,
        "radio": "gsm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          10.8984375,
          52.4827802
        ]
      }
    }
  ]
}
```

Reference for mime type: http://www.iana.org/assignments/media-types/application/vnd.geo+json

**Comment by garvankeeley** [comment]
The suggested scheme  `/v1/cell/13/2288/2989.geojson` would be ideal. The simplest approach may be to have only one zoom level supported for now. The zoom level 12 (~2.5km^2) or 13 (~5km^2) would seem like a reasonable size: http://wiki.openstreetmap.org/wiki/Zoom_levels

We would want to have stumbler loading these tiles in a throttled fashion, so we aren't hitting the server too hard; the stumbler would progressively fill in the map also caching the cell data.

**Comment by hannosch** [comment]
The main person who wanted to implement this has left the project. So realistically this won't happen.
