### ISSUE TITLE
Investigate lac>=65534

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#367]
The [LAI (location area identification) for UMTS](http://www.etsi.org/deliver/etsi_ts/123000_123099/123003/12.04.01_60/ts_123003v120401p.pdf#page=24) mentions LAC 0x000 and 0xfffe as special reserved values stating:
"These reserved values are used in some special cases when no valid LAI exists in the MS (see 3GPP TS 24.008 [5], 3GPP TS 31.102 [27] and 3GPP TS 51.011 [9])."

We already filter out LAC = 0, but do allow both LAC = 65534 and 65535 for all networks. And we do have network entries in our data for both of these LAC values (~80 and ~2000 respectively).

We need to figure out what these special cases are and if we should tighten our filter. We also need to see if similar special cases exist for other radio types.

**Comment by hannosch** [comment]
Closed via #399.

**Comment by fenuks** [comment]
I still have this error on the latest git version trying to import data from OpenCellId, e.g. importing this row triggers the error:

UMTS | 260 | 3 | 65534 | 131882621 | 0 | 19.03656 | 50.764389 | 1000 | 2 | 1 | 1366435678 | 1366435678 | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by szjozsef** [comment]
In my personal experience to be abe to import the data from OpenCellId, I have to filter out any data with:
area = 65534
OR
area = 65535
OR
area = 0
OR
cell = 2147483647
OR 
cell = 0
OR
radio = CDMA
OR
radio = 0
OR
cell > 268435456

And you have to have the mobile_codes json's (countries.json, mnc_operators.json) updated at least to the latest version from the https://github.com/mozilla/ichnaea/tree/main/mobile_codes/json repo
Then the import will work (even the full import, not just the daily)

**Comment by fenuks** [comment]
Thank you. I've managed to import data I wanted (not a full import) by filtering out everything with cell or area >= 65534, and cell = 0.
