### ISSUE TITLE
Stats for Fennec contribution

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/ichnaea#368]
Data I am looking for 
* Reports per day
* WiFis per day
* Cells per day
* newly discovered Cells per day
* newly discovered WiFis per day (not really that interested in this particular stat)

**Comment by hannosch** [comment]
We got most of this done and have metrics to track data uploads per API key. We don't have metrics to tie newly discovered stations to API keys and it's still difficult to do that. We didn't really need this so far, so closing as wishlist/wontfix.
