### ISSUE TITLE
Map: Add search in map

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#372]
Add possibility to search in map for country/address/location.

Example:
https://carto.rudloff.pro/gsm (at the top on the right)

When you search a location in a town it is very complicated to zoom to this point.

**Comment by hannosch** [comment]
Mapbox (our map provider) changed the pricing structure on this a while ago, making "ephemeral" geocodes free to use on mapbox basemaps. Which is all we need / want for this project.
