### ISSUE TITLE
[Question/Suggestion] passive submission

### ISSUE THREAD

**Issue by VolMi** [mozilla/ichnaea#374]
As a stumbler I always think it's a pity that we will never be able to get all the cells and WiFis. This is mainly because we are too few people and also fundamentally, because a lot of WiFis in larger buildings are out of GPS reach. E.g. I was in a hospital a few hours ago with >100 (!) WiFi APs visible simultaneously but far away from any free sky.

I was wondering if ichnaea does already make use of *Geolocate requests* to actually enhance its own database? Call it a *passive submit* if you will.

The idea is simple:
Assume that ichnaea has entries A and B in its database and a user makes a Geolocate request providing cells/WiFis A,B,C,D,E…
If any cells in this request are still unknown it would be plain silly to completely ignore their existence and their vicinity to A and B: A further Geolocate request with cells/WiFis D,E,F,… would fail if they have not been actively stumbled.

So I would suggest (if it's not done already) to build something like a passive database. It is fed with info from plausible and successful Geolocate requests for cells that do not yet exist in the main database.
Further requests with no hit in the main database could then fall back to the passive data. In case of WiFis, this is propably even very accurate.

If Mozilla's Geolocation endeavour is successful, there will always be a much larger crowd of Geolocate users than feeding stumblers.

**Comment by VolMi** [comment]
Your latter remark explains why this client side smartness probably should not be done at all: A lot of complexity with huge error amplification for little benefit.

Concerning the number of active users: I have thought that mozilla would change ````geo.wifi.uri```` in Firefox as soon as the own geolocation service is deemed usable.

Good that you had the idea already. I like that it's simple, server-side and that you likely get good accuracy without sensor-smartness or triangulation, for WiFi at least.

**Comment by hannosch** [comment]
Closing this issue as it is "too broad". We'll look into gathering data without GPS fixes in the future, which once we do will create a couple real tickets appropriate for the issue tracker. I'm not a fan of keeping "stories" or broad ideas in an issue tracker, as it's the wrong tool for the job.
