### ISSUE TITLE
Open Badges

### ISSUE THREAD

**Issue by rodmoreno** [mozilla/ichnaea#375]
Suggest the possibility of rewarding users weekly top of the leaderboard by an [Open Badge](http://openbadges.org), is a project of the foundation and we could encourage more communities and people submit data for the MLS.

**Comment by sshvetsov** [comment]
Neat idea. People like earning achievements. I would also recommend to reward total number of observations collected, eg: badge for 10,000, 100,000, etc.

**Comment by hannosch** [comment]
Moved to new leaderboard project.
