### ISSUE TITLE
Guess MCC from system id for CDMA

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#377]
As part of mozilla/MozStumbler#1372 we found that we most often don't get a reliable mcc for CDMA networks. Instead we have a system id in the mnc field which is globally unique on its own, so we can guess the missing mcc from it.

Today we either get a false (taken from SIM card if present) or no (mcc = -1) value for CDMA reports. We need to accept those and then try to guess the mcc based on the system id.

**Comment by hannosch** [comment]
Given the overall low number of CDMA cells in the world and its continuing decline, we decided to stop supporting the standard.

**Comment by E3V3A** [comment]
The best statement about CDMA I've heard to this date. :)
