### ISSUE TITLE
Use a data validation framework

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#378]
The current validation code is written from scratch rather than using some kind of validation framework.  This makes it difficult to reason about how a given field is validated or track down where a validation failure is occurring.  There are many well established frameworks for validating data, we could use the SQLAlchemy model level validation, something pyramid provides, or something more standalone like:

https://github.com/schematics/schematics

http://wtforms.readthedocs.org/en/latest/

**Comment by hannosch** [comment]
Or we can use the one we already use in more places -> http://docs.pylonsproject.org/projects/colander/en/latest/

We do need a validation framework that is independent of any storage models, as we validate data as part of the data pipeline when all we have is blobs of JSON to work with.

**Comment by jaredkerim** [comment]
Colander it is!
