### ISSUE TITLE
Investigate cellid=65535 for GSM

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#383]
https://github.com/Rudloff/mls-cell-map/issues/21

**Comment by hannosch** [comment]
Thanks for the report, we actually discovered the same thing as part of #367. Closing as duplicate.

**Comment by Gitschubser** [comment]
At the moment exists 1523 cellids with the value 65535. 
#367 filters only the lac but not the cellid?

Short examples T-Mobile (262-1) with many cellids with value 65535:
GSM,262,1,17740,65535,,8.5775167,49.4999508,15748,3170,1,1383587563,1408453593,
GSM,262,1,17703,65535,,8.44739,49.5527879,23819,87,1,1383604176,1408453593,
GSM,262,1,6478,65535,,8.6023761,50.0169615,13118,1205,1,1383604304,1408453593,
GSM,262,1,4209,65535,,8.4392682,49.95904,27990,1332,1,1383604304,1408453593,
GSM,262,1,4224,65535,,8.5992521,49.8379305,23390,5027,1,1383604372,1408453593,
GSM,262,1,17695,65535,,8.51545422984,49.4633733894,31586,3867,1,1383604674,1419612502,
GSM,262,1,4228,65535,,8.6665961,49.630824,22667,612,1,1383607082,1408453593,
GSM,262,1,17684,65535,,8.7106335,49.0230379,483,19,1,1383607086,1408453593,
GSM,262,1,21105,65535,,8.7133276,49.0221253,79,8,1,1383607086,1408453593,
GSM,262,1,17744,65535,,8.7420117,49.270429,14322,313,1,1383607099,1408453593,
GSM,262,1,21102,65535,,9.05311605047,48.8042176334,10018,317,1,1383607102,1419612713,
GSM,262,1,17741,65535,,8.6777079,49.4999977,12426,152,1,1383607117,1408453593,
GSM,262,1,6480,65535,,8.716492,50.113186,1913,176,1,1383607124,1408453593,
GSM,262,1,6481,65535,,8.7013872,50.111404,5391,530,1,1383607124,1408453593,
GSM,262,1,6486,65535,,8.7295417,50.1016956,9883,957,1,1383607124,1408453

**Comment by hannosch** [comment]
Oh, this is indeed about cell id and not the lac, so not a duplicate.

Based on what you said in Rudloff/mls-cell-map#21 this looks like this might be another case of a special token value. Maybe the TS documents I linked to in #367 explain this as well somewhere.

**Comment by sshvetsov** [comment]
I've often seen such behaviour on Android phones that can show GSM neighbour cells (eg. HTC One). The neighbour cells often have value CID=65535, but I've never seen a current cell with such value.

**Comment by hannosch** [comment]
Ok, I couldn't find any references in the TS documents for this. We already have a code path that rejects cid=65535 when we don't have a valid lac to go with it. Looks like we should extend that to always reject cid=65535 even if we have a valid lac.

In `ichnaea.models.cell.ValidCellKeySchema.deserialize` I'd re-order the last two checks and change them to:

```
# Treat cid=65535 as missing for GSM networks
if (data['radio'] == Radio.gsm
        and data.get('cid', None) == 65535):
    data['cid'] = self.fields['cid'].missing

# If the cell id >= 65536 then it must be a umts tower
if (data.get('cid', 0) >= 65536
        and data['radio'] == Radio.gsm):
    data['radio'] = Radio.umts

return super(ValidCellKeySchema, self).deserialize(data)
```

To finish this, we need a migration step to delete all radio=0, cid=65535 rows from the cell table, decrease the cell stats by the number of deleted rows and trigger recomputation of the affected cell areas.

The last bit is tricky, as we need access to Redis from inside the alembic / migration environment, which isn't set up so far. Maybe we can add a new `redis_url = ...` setting into the alembic.ini, read it as part of the ichnaea.alembic.env.py file and set up a RedisClient manually there. Then feed all the affected area objects into the `ichnaea.data.area.enqueue_areas` function using that redis client at the end of the migration step.

**Comment by sshvetsov** [comment]
Hey Hanno, I double checked my personally collected cells from around the world and I'm afraid my earlier statement was incorrect. In fact, I found 17 cells in my database that have cell id 65535 and seem to be valid current cells. Four are from Hutchison (3) in Indonesia and rest are from China Mobile:

460,00,9330,65535
460,00,9340,65535
460,00,9363,65535
460,00,9365,65535
460,00,9366,65535
460,00,9381,65535
460,00,9721,65535
460,00,10129,65535
460,00,10132,65535
460,00,10144,65535
460,00,10145,65535
460,00,10166,65535
460,00,10173,65535
510,89,9025,65535
510,89,9201,65535
510,89,9250,65535
510,89,9260,65535

So, it seems ignoring and deleting all GSM cells with Cell ID = 65535 is not a good idea.

**Comment by Gitschubser** [comment]
I have created a .kml from all cellids with the value 65535.
The cellids from my provider does not exist in this area (based on my knowledge) but there are logged in my database.

![65535](https://cloud.githubusercontent.com/assets/7853509/6885978/8737d51c-d62e-11e4-8c60-158a41bbb7bc.jpg)

**Comment by sshvetsov** [comment]
Just to clarify, I have seen Hutchison IDN use non-existent LAC and Cell ID 65535 in its neighbour lists. Those were not real LACs/cells and could be ignored (if we can figure out a reliable way to identify them as such).

However, I believe it is also possible to have a real GSM cell with Cell ID 65535, and the cells I posted earlier are samples of that. The samples were collected with netmonitor, BTW, and seem to be present in Google's DB.

On a related note... Since neighbour lists for GSM cells are configurable by operator/contractor, they could be (intentionally?) incorrect or outdated. Perhaps, the geosubmit API should provide (require?) a way to specify whether each submitted cellTower is a neighbour, or is the serving cell? Then cell data can be assigned different levels of trust.

**Comment by E3V3A** [comment]
Google API for providing Neighboring Cells IDs are broken on most Samsung Phones and many others. In addition the CID 65535 is reserved and may be shown when there is no CID available. For example, in the short moment during RAT change. Thus all CID 65535 should be ignored, unless the phone/device is actually "camping" (staying longer than ~3-5 seconds) on that CID, in which case you might be subject to an IMSI-catcher.
