### ISSUE TITLE
Configure Python's logging module

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#385]
Today we don't explicitly configure Python's logging module. We should do that, at least some sort of hard-coded basicConfig. We do want to see critical and error and maybe even warning messages on stderr, so we can see them in the server logs. Probably this needs to be done separately for gunicorn, celery and the web app.

We should have sentry reporting for Python exceptions, but those don't cover simple log.error/log.warning messages being emitted.

**Comment by jaredkerim** [comment]
I was speaking to Toby earlier today and we were talking about logging our data validation layer.  I'm not sure if we do any such logging presently (I think we don't?) but one thing we get access to with using Colander to perform validation is the specific validation errors that a cell or wifi measurement triggers.  We could log this to find trends.  Additionally, we could send information from the client about its hardware (device manufacturer, device model, radio manufacturer, etc) and use that to find more interesting things about failures or data transformations.

**Comment by hannosch** [comment]
Actually celery does hicjack and configure Python's logging module on its own, so doing it manually in for the webapp process is enough.
