### ISSUE TITLE
Add a track id, to tie multiple reports together

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#386]
GPS locations are sometimes rather bad and inaccurate. One way to improve them is by looking at a track of reports and smooth/correct locations based on a trajectory.

Today we only store each report with a unique report uuid, but we don't store any ids for a collection of reports. When doing this we need to make sure we don't inadvertently add a unique user id.

As a compromise we could start adding a unique id to each uploaded batch of reports. For Mozilla Stumbler this typically means giving 50 reports the same track id. We already split up the processing of batches by 100 reports, in order to limit their processing chunk size. We could make sure to only assign a track id to each such chunk of a maximum of 100 reports, so even if a client sends us more than 100 reports at the same time, we don't tie too many reports together.

In the future we could allow the client to send us an optional track id. The client could additionally split things up by time interval, so it wouldn't tie reports together when there's some X minutes break in between the reports. On the service end we only get to see a timestamp rounded down to a monthly resolution, so we can't do this after the fact.

**Comment by garvankeeley** [comment]
Very easy to do on the stumbler. +1

**Comment by hannosch** [comment]
One more use-case for this is to export our data to a project like http://opentraffic.io. They need a "vehicle id", GPS lat/lon and precise timestamp. Their vehicle id is really just a way to tie multiple positions together so they can derive speeds estimates for road segments from it. What I described initially as a track id should support this use-case.

**Comment by kolesar-andras** [comment]
+1
