### ISSUE TITLE
Reconcile accuracy, altitude, altitude_accuracy as Float/Integer

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#389]
The fields accuracy, altitude, and altitude_accuracy are stored as Integers in the database, however, the validation layer validates them as floats.  We need to reconcile when and where they are ingested as floats depending on the API, and are converted into Integer before they are persisted.

@hannosch can you suggest the exact locations where this should be addressed?

**Comment by hannosch** [comment]
This seems to be wrong in a couple places. The geosubmit API is meant to take in float values in its accuracy fields. Pretty much everything else is supposed to take in and spit out integer values.

I can see some wrong tests for `service.search.tests.test_views`, which test for floats, where they shouldn't.

For geosubmit, I'd convert from float to int inside the geosubmit view code, specifically in `service.geosubmit.views.process_upload` where it maps the external dict representation into our internal dict representation, changing lines like `'accuracy': batch['accuracy'],` to 'accuracy': int(batch['accuracy']),

For our internal code, we probably should generate int's for accuracy related data immediately. Say for example in `geocalc.maximum_country_radius` and `geocalc.distance`.
