### ISSUE TITLE
Remove import code

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#390]
Remove the import code found here:

https://github.com/mozilla/ichnaea/blob/master/ichnaea/scripts/importer.py

**Comment by hannosch** [comment]
If we want to do import of data, we should parse external data files and feed them via HTTP requests into our service like everything else. That way it goes through the exact same logic path as all the usual data. Scripts for doing this sort of thing could live in https://github.com/cpeterso/stumbler-tsv or a fork thereof.
