### ISSUE TITLE
Split ValidWifiSchema into ValidWifiSchema and ValidWifiMeasureSchema

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#391]
Right now we have a single validator for Wifi and Wifi measure because the tests present both the wifi and measure data in a single blob.  We should split these so that the Wifi and WifiMeasure schema's closely match the database fields on each model and alter the tests accordingly.

**Comment by hannosch** [comment]
I've actually taken care of this while splitting up the db models into different classes and associating the data schema with them.
