### ISSUE TITLE
Get rid of data.tasks.incomplete_measure

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#395]
Get rid of this:

https://github.com/mozilla/ichnaea/blob/master/ichnaea/data/tasks.py#L302-L315

Fold it into the validation layer.

**Comment by hannosch** [comment]
The code moved a bit and is now at `ichnaea.data.observation.CellObservationQueue:incomplete_observation`.

**Comment by hannosch** [comment]
A similar construct is now in the export/import OCID code.

**Comment by hannosch** [comment]
The incomplete_observation method is gone. There's something similar in exports.tasks, but that can be replaced as part of #446.
