### ISSUE TITLE
Import data from openbmap project

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#401]
Import data from project Openbmap at radiocells.org could be interesting (same import as opencellid)?

Cell database:
http://radiocells.org/downloads/cell_data

Stats:
http://radiocells.org/stats/cell_providers

License:
The cell data is licenced Creative Commons Attribution-ShareAlike 3.0 Unported.

**Comment by hannosch** [comment]
Interesting, seems there is a new beta website up for the project. The project had a long period of inactivity and the maintainers didn't answer the emails opencellid sent them.

The license means we'd need to keep the data separate from the rest as well, and the data format is custom, so we'd need to write yet another importer. Given the comparatively low overall data volume, this isn't high priority for now.

**Comment by E3V3A** [comment]
Yep, very small indeed. But good to know others are interested in getting this mapped out.

**Comment by Gitschubser** [comment]
The project Openbmap is at an early stage.
This month collect 12 users only 12029 cells in Germany, Croatia, USA, Spain, Belgium, Austria, Sweden and Taiwan.
It is interesting to see the progress over the following months.
In the next 6 months MLS is the new leader before wigle.net and opencellid.de. :-)

**Comment by Djfe** [comment]
Could we also have such statistics? (grouped by providers instead of countries)

I think that would be a great addition

importing the db itself will be quite some hassle
I took a look at the file format: it's a compressed folder containing several dozen xml files with cell data

the .csv file of MLS and OpenCellID is much easier to handle and probably makes it easier to store a lot of cells in it than this format.

**Comment by hannosch** [comment]
I did a one-time comparison between the current openbmap/radiocells dataset and the MLS and OCID datasets. Out of the 500k cells that radiocells has, there are only 50k which have complete enough information and are not in one of the two other datasets.

So at this point radiocells would increase our database by ~0.3% or by about the new cells we discover in a single day. Unless the radiocells project grows significantly, it's not worth integrating.
