### ISSUE TITLE
Investigate cellid=2147483647 

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#404]
The cellid 2147483647 has 671 matches in the cell export.
This value is strange.

http://wiki.opencellid.org/wiki/Talk:Next_steps

**Comment by Gitschubser** [comment]
Examples:

UMTS,262,1,14728,2147483647,324,7.626578,52.6883646667,16827,6,1,1422572203,1423518460,
UMTS,262,1,1927,2147483647,379,7.78022075,52.832683,14371,4,1,1422815903,1422815908,
UMTS,262,1,17288,2147483647,190,12.93213675,48.30437025,15388,4,1,1422989869,1423299561,
UMTS,262,1,17579,2147483647,175,11.60711375,49.75892125,31840,4,1,1422991887,1422991908,
UMTS,262,1,6560,2147483647,331,8.92534425,50.29205075,1375,4,1,1423160148,1423774573,
UMTS,262,1,35221,2147483647,139,13.7724605,51.0927875,2329,2,1,1423515453,1423728368,
UMTS,262,1,5769,2147483647,63,7.2143011,51.5912497,8411,10,1,1423577478,1423659916,
UMTS,262,1,17586,2147483647,286,11.012682125,49.5494135,3908,4,1,1423606197,1423606228,
UMTS,262,1,17596,2147483647,179,11.1229213333,49.5462766667,972,6,1,1423606197,1423606200,

**Comment by Gitschubser** [comment]
OCID same problem:
UMTS,226,10,2147483647,2147483647,,26.047528,44.601688,0,4,1,1387581383,1387584684,
UMTS,214,1,2147483647,2147483647,,-4.53479,42.01771,0,1,1,1387630628,1387635338,
UMTS,214,1,2147483647,2147483647,,-4.53479,42.01771,0,1,1,1387630628,1387635338,
UMTS,262,1,2147483647,2147483647,,8.988726,53.039622,0,3,1,1387526413,1388930530,
UMTS,262,1,2147483647,2147483647,,8.988726,53.039622,0,3,1,1387526413,1388930530,
UMTS,234,20,2147483647,2147483647,,-0.25464,51.709198,0,7,1,1387644683,1389279984,
UMTS,234,20,2147483647,2147483647,,-0.25464,51.709198,0,7,1,1387644683,1389279984,
UMTS,238,6,2147483647,2147483647,,12.53672,55.701028,0,1,1,1387684822,1387684938,
UMTS,238,6,2147483647,2147483647,,12.53672,55.701028,0,1,1,1387684822,1387684938,

The filter for lac and cellid works not very good:
LAC/TAC/NID 	must be in the range of 1 to 65535 
CID 	must be in the range of 1 to 268435455 for UMTS and LTE

**Comment by E3V3A** [comment]
No, it's not strange at all, it's simply: `0x7FFF FFFF`, the default from improper API support for UMTS, where only PSC are shown, and not always CID/LAC. most usually found on Damnsung phones.

**Comment by Gitschubser** [comment]
Ok, so it make sense to change the filter, delete all rows with this value and change the stats?

**Comment by E3V3A** [comment]
Probably originating from [RILConstants.java](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.4.4_r1/com/android/internal/telephony/RILConstants.java?av=f):
```int MAX_INT = 0x7FFFFFFF;```

**Comment by hannosch** [comment]
Sounds like for UMTS networks, we should just treat cid=2147483647 the same as if we'd get no value at all for the cid field.

**Comment by hannosch** [comment]
We actually took care of this in the meantime, by restricting the cid to 28 bit values.

**Comment by Gitschubser** [comment]
Is it possible to delete the currently more than 8000 cellids with value 2147483647?

**Comment by Gitschubser** [comment]
Add cellid 2147483647 to the blocklist?

**Comment by hannosch** [comment]
I've manually removed these cells from the database. They shouldn't show up in the next full cell export anymore.
