### ISSUE TITLE
Geosubmit documentation issues - missing age

### ISSUE THREAD

**Issue by crankycoder** [mozilla/ichnaea#408]
The `age` field is listed as optional but not well defined what the meaning is, or what units it should be in.

**Comment by crankycoder** [comment]
Hrm... we don't seem to have age at all for our CellInfo objects in the stumbler.  Maybe we've never used this.

**Comment by hannosch** [comment]
The cell `age` field is actually part of Google's geolocate schema, we just never used it anywhere. We also don't actually store it in the database yet. It's optional so leave it out :)
