### ISSUE TITLE
add libstumbler info to website

### ISSUE THREAD

**Issue by Djfe** [mozilla/ichnaea#412]
LibStumbler should be mentioned on the website:
https://location.services.mozilla.com/apps

Maybe a short description including a link to the wiki for further information:
https://github.com/Mozilla/MozStumbler/wiki/libstumbler-design-doc

**Comment by hannosch** [comment]
There's also the still empty https://github.com/mozilla/MozStumbler/wiki/Using-libstumbler - I'll wait for a page that explains how to use the stumbler lib here. The design doc is only really useful for people wanting to contribute to the development of libstumbler.

**Comment by hannosch** [comment]
I've added it over on the wiki at https://wiki.mozilla.org/CloudServices/Location/Software where everyone can make edits and maintain the list.
