### ISSUE TITLE
Update geolocate request API documentation

### ISSUE THREAD

**Issue by sshvetsov** [mozilla/ichnaea#419]
As per discussion in MozStumbler issue mozilla/MozStumbler#1556, the [documentation](https://mozilla-ichnaea.readthedocs.org/en/latest/api/index.html#geolocate) for geolocate JSON request needs to be updated, since it appears to have several diviations from [GLS API](https://developers.google.com/maps/documentation/business/geolocation/).

MLS geolocate request JSON appears to support properties, which are not defined in GLS API, like:
* latitude
* longitude
* timestamp
* cellTowers[].psc
* cellTowers[].asu
* cellTowers[].radioType
* wifiAccessPoints[].frequency
* wifiAccessPoints[].signalStrength

It is unclear whether MLS geolocate request JSON supports all properties, which are defined in GLS API, like:
* homeMobileCountryCode
* homeMobileNetworkCode
* radioType
* cellTowers[].age
* wifiAccessPoints[].age
* wifiAccessPoints[].channel
* wifiAccessPoints[].signalToNoiseRatio

**Comment by sshvetsov** [comment]
Noticed that #376 mentions the homeMobileCountryCode and homeMobileNetworkCode fields from the GLS API specification, so referencing the related issue here.

**Comment by hannosch** [comment]
I think I addressed all of this in 55ed99c16eb252d3350b14e611cd61d515f106e3. The extra latitude/longitude/timestamp fields aren't part of our geolocate API anymore. The others should all be documented.
