### ISSUE TITLE
Geoip-only when wi-fi or cell geolocation is expected

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/ichnaea#420]
This bug was filed in stumbler by a user:
https://github.com/mozilla/MozStumbler/issues/1569

If we are getting more of these reports, then we should be concerned there is a bug. An isolated report is difficult to follow up on because a particular area may not have wi-fi or cell geolocation, and geoip *may* be the correct geolocation source.

**Comment by lua86** [comment]
Sorry for not filing here myself, I don't check github mail often.
-I've previously stumbled the area, both with this dual-sim device and other, single-sim devices.
-This also happens near the capital of the province when cell-only (checked yesterday, forgot taking screenshots)
-One of the sims is dead. (May that be part of the problem?)(Should I try with two working sims?)

**Comment by lua86** [comment]
Further testing: stumbled on city with both the 'faulty' SIM card and wi-fi disabled. Not even one report.

**Comment by lua86** [comment]
More city testing: cell count is keeping at zero, I'll report back at mozstumbler.

**Comment by hannosch** [comment]
Sounds like this was a scanner bug, as commented here https://github.com/mozilla/MozStumbler/issues/1569#issuecomment-87451470
