### ISSUE TITLE
pep8 validation

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#427]
We've got a bunch of failing pep8 validations, should clean those up.

**Comment by hannosch** [comment]
I have flake8, flake8-immediate, pep8 and pep8-naming installed, with a flake8 config file of:
```
[flake8]
ignore = E226,N802,N806,N811
max-line-length = 79
max-complexity = 20
```
That tells me we currently have no warnings at all. What kind of config do you have?

**Comment by jaredkerim** [comment]
Ah what happened was I installed pep8-naming and it started catching N802 errors, which you have disabled in your flake8 config.  I'll update my config to the same thing.
