### ISSUE TITLE
question: e-plus and o2 joined their mobile networks (german providers)

### ISSUE THREAD

**Issue by Djfe** [mozilla/ichnaea#428]
Is this change going to affect MLS in any way? -> new cell ids, maybe? that would make a good chunk of our data useless (we could delete networks, that we know don't exist anymore)

Or are the cell towers of both providers still returning the id they had before the change and technically the providers just allow roaming in each others networks now?

**Comment by hannosch** [comment]
All cell ids contain both a country code and a network / operator code. You can see those for example at https://en.wikipedia.org/wiki/Mobile_country_code#Germany_-_DE

Both E-Plus and O2 have multiple of these mnc assigned to them. What happens at first, is that all of these codes are just taken over by one company and so their clear text name changes. That in itself has no impact on the technical cell ids or on us. And yes, they also reconfigure their networks, so all their subscribers get told which mnc they can now use for free.

Later on these companies may decide to consolidate their networks and remove redundant cell capacity where both of them have cell antennas / towers deployed. But that's a process which is going to take a long time. I'd expect that to happen with the same sort of frequency in which operators optimize or build out their networks. They have to figure out who owns what exact frequency bands in which region, where each of them have cell towers, where there is demand or optimization potential and then on a area by area basis reassess what to do.

Essentially there is no advantage for them to change the mnc from one value to another, so there's not going to be any sort of switch-over date where suddenly all the cell ids change. The only advantage over time is the reducing the need for physical infrastructure. But physical things change slowly.

**Comment by Djfe** [comment]
Thx for your detailed answer! :)
