### ISSUE TITLE
Bad cell ids when switching operators

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#431]
Got a report via our OCID friends. Apparently when switching from one cell operator to the next, there can be a short timeframe, in which some of the cell id parts are already from the new operator, but some are still from the old. One specific example was (obfuscated lac/cid values):

GOOD Free Mobile cell ID:

Free Mobile
MCC: 208 (France)
MNC: 15 (Free Mobile)
LAC: 1234
cell ID: 123456789

BAD cell ID:

Free Mobile
MCC: 208 (France)
MNC: 15 (Free Mobile)
LAC: 1234
cell ID: 34567

GOOD Orange cell ID:

Orange
MCC: 208 (France)
MNC: 1 (Orange)
LAC: 23456
cell ID: 34567

**Comment by E3V3A** [comment]
Interesting. Perhaps your your OCID friends could enlighten us with what device this data was collected with? An Android app? (Which?) What phone and hardware?
