### ISSUE TITLE
Add explicit fallback choices to geolocate API

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#438]
This is an extended spin-off from #421, where I said:

* In the fallback query, use the custom syntax and add `"fallbacks": {"lacf": 1}` to the geolocate query (see http://combain.com/api/ fallbacks or the WCDMA lacf example.

Instead of just explicitly doing this for the queries we are sending to the fallback provider, we should just add proper support for specifying fallbacks to our own query API and than pass through those fallback choices to the fallback provider.

This would allow someone to call our service and disable either the IP fallback and/or the cell area fallback.

This means our own geolocate query should get one more top-level mapping called `fallbacks`, on the same level as cellTowers/wifiAccessPoints. An example would be:

```
{
	"cellTowers": [{
		"radioType": "gsm",
		"mobileCountryCode": 240,
		"mobileNetworkCode": 1,
		"locationAreaCode": 3012,
		"cellId": 0
	}],
	"fallbacks": {
		"lacf": 1
	}
}
```
Combain does support a lot of different fallback options, as documented at http://combain.com/api/#1423734237921-5-5 (under the fallback parameter tab). Not all of those make sense for us, so I'd limit our support to just two:
* lacf (triggers using our cell_area/ocid_cell_area tables, and forwards the option to the fallback provider)
* ipf (use the IP address of the remote, don't support explicitly passing in a different IP address at this point), if disabled don't use our geoip provider to determine a location (might still be used to determine a country for metrics purposes).

In order to not change our current behavior, I'd default both options to true. As another complication, we don't want to send the ipf key in the outbound query to the fallback provider, but just the lacf key.

The second part of this is adding a `fallback` key to our response, for example:
```
{
	"location": {
		"lat": 59.393072,
		"lng": 18.160667
	},
	"accuracy": 46617,
	"fallback": "lacf"
}
```
This fallback key would only be set if the returned result is based on one of the fallbacks and if so is either set to lacf or ipf. The most complicated case here is that we'd end up using the location from the fallback provider and it was based on a lacf fallback, so our response should also say fallback:lacf.

I wouldn't add any of this to our old search API. In the request I'd accept both `0/1` and `true/false` as valid arguments.

**Comment by jaredkerim** [comment]
Pre squashed r? @hannosch
