### ISSUE TITLE
Replace LocateTransform with an internal class based representation

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/ichnaea#444]
Presently, we receive locate queries into both v1 and v2 in different data encoding schemas, and these are reconciled using the LocateTransform(ReportTransform) class which parses them into a consistently named set of dictionaries.  We would like to replace this with a set of schema specific deserializers which deserialize into an internal object representation (similar to a DB Model representation, but purely in memory).  Potentially overloading Colander, or just using NamedTuples, or something.

**Comment by hannosch** [comment]
As of 377d419ea440b6b167c08b21793678721b0e0c7d this is actually done.
