### ISSUE TITLE
Wrong map elements - difference from OSM and the version we use

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/ichnaea#448]
Pink - the missing component 
Green - my diverted road ( through a field to get back)
![screenshot_2015-06-09_22_42_42](https://cloud.githubusercontent.com/assets/1391451/8069149/27af2e18-0f01-11e5-91f8-2e68291663bc.png)

**Comment by ioana-chiorean** [comment]
Gmaps 
![screenshot 2015-06-09 23 43 50](https://cloud.githubusercontent.com/assets/1391451/8069200/6790e4ae-0f01-11e5-9a00-5d4b8c18b2d6.png)

**Comment by hannosch** [comment]
The dark basemap we use was created by mapbox for us once. I think it was generated as a pile of static pngs based on the OSM data that was current back then. But it isn't actually updated based on newer OSM changes.

To fix this we have to figure out how to get a basemap that is updated continuously.

**Comment by hannosch** [comment]
I think this should be solved by using the `mapbox.dark` map provided by mapbox. Code changes are done in 902f781e135eb903b37dce0b2f3ce527d403d8a5.

This won't be rolled out to the production website for some time, but locally this looks good.
