### ISSUE TITLE
Update Cell Fields in documentation -> Network Type UMTS to WCDMA

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#457]
The file has changed the value from UMTS to WCDMA.
The documentation reads as follows "One of the strings GSM, UMTS, LTE or CDMA".
Correct is "One of the strings GSM, WCDMA, LTE or CDMA"

**Comment by Gitschubser** [comment]
OCID use the value UMTS, not WCDMA. 
radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal
UMTS,262,2,801,86355,,13.28527,52.521711,37,7,1,1282569574,1300175362,-91

Parameter 	Data type 	Description
<radio> 	string 	Network type. One of the strings GSM, UMTS, LTE or CDMA.

**Comment by hannosch** [comment]
I've fixed the code so it again outputs UMTS and conforms to the docs. This won't hit the production system for another week.
