### ISSUE TITLE
Adding SSID and Encryption Method information to Wifi Table

### ISSUE THREAD

**Issue by YastaB** [mozilla/ichnaea#463]
Would it be useful if we add those information to the Wifi table? 

So we can differentiate the wifi access points  with those info.
I think it can be useful for future features.

**Comment by hannosch** [comment]
We aren't allowed to collect the SSID, as it can contain personal data like the names of people ("John Smith's Wifi") and the SSID isn't technically required to distinguish WiFi networks from each other.

I don't know why we would want to collect the encryption method. We could put up some statistics about how widespread WPA2 adoption is now, but that would just satisfy some curiosity. It wouldn't help with the purpose of this service. At the same time this information could be used to find vulnerable or open WiFi networks, which is data I'd rather not have at all, so we couldn't accidentally leak it.

**Comment by YastaB** [comment]
Thank you for the clear explanation. 
I am also curious that using these information is not legal? 
I mean, Are these kind of things controlled by an organization?     

Thank you in advance.

**Comment by hannosch** [comment]
Collections of personal data and what constitutes personal data is something governed by law in each country. In addition at Mozilla we follow our core set of data privacy principles (https://www.mozilla.org/en-US/privacy/principles/), one of them can be paraphrased as "only collect what we need".

If you are interested, I wrote a blog post (http://blog.hannosch.eu/2013/12/mozilla-location-service-what-why-and.html) a long while ago about this and there's also the Dutch DPA in-depth article that triggered most of the privacy protections that most location services adhere to today (https://cbpweb.nl/sites/default/files/downloads/mijn_privacy/en_pb_20110811_google_final_findings.pdf).
