### ISSUE TITLE
collect wifi stats: frequency, protocols, etc.

### ISSUE THREAD

**Issue by Djfe** [mozilla/ichnaea#465]
will wifi stats be collected in the future (2,4/5ghz networks, a,b,g,n,ac protocol etc.)
that could be interesting for the wifi stats list

**Comment by hannosch** [comment]
Someone asked for the collection of WiFi encryption information over in #463 and my answer is the same:

These kind of additional metadata about WiFi networks satisfy our curiosity, but there isn't a real need to collect these for the purpose of this service. We are following the "only collect what you need" guideline from Mozilla's data privacy principles (https://www.mozilla.org/en-US/privacy/principles/). As long as there isn't a clear need to collect these, we shouldn't do it.

At the same time a clear purpose is also needed to justify spending time on working on this. With the limited resources we have for this project, we just won't get to do any nice-to-have's.
