### ISSUE TITLE
Enable CORS on /v1/country endpoint

### ISSUE THREAD

**Issue by jbuck** [mozilla/ichnaea#468]
Hi there! We'd like to use Ichnaea for auto-detecting country on donate.mozilla.org. The only blocker to doing this would be to enable CORS on the endpoint so that visitors to donate.m.o could successfully complete the request.

Easy way to test in your browser whether it's working successfully or not:

`fetch("https://location.services.mozilla.com/v1/country").then(function(response) { console.log(response); }).catch(function(ex) { console.log(ex); });`

**Comment by hannosch** [comment]
Ah, right. I'll get to this shortly. So far we have only been used from inside the guts of Firefox Desktop, not directly from web pages.

**Comment by jbuck** [comment]
@hannosch Great, thank you!

**Comment by hannosch** [comment]
Got most of the functionality in place, hoping to get this down and to stage this week, if all things go well it'll land in early production next week.

**Comment by jbuck** [comment]
@hannosch awesome! If you'd like us to test staging for you, just mention me when that's deployed

**Comment by hannosch** [comment]
@jbuck can you try and see if https://location.stage.mozaws.net/v1/country works for you now?

**Comment by jbuck** [comment]
@hannosch Working great with CORS!

`fetch("https://location.stage.mozaws.net/v1/country").then((response) => { return response.json(); }).then((json) => { console.log(json); }).catch((ex) => { console.log(ex); }); `
