### ISSUE TITLE
Confusing sentence about Firefox OS support

### ISSUE THREAD

**Issue by rugk** [mozilla/ichnaea#471]
(continuing the [Android-repo](https://github.com/mozilla/MozStumbler/issues/780#issuecomment-163355647))

On https://location.services.mozilla.com/apps there is written:
> Integration of this service into Firefox OS is an ongoing process. If the specific Firefox OS device uses this service depends on a number of factors including which chipset is used in the device, which manufacturer built the device and via what partner and channel it was sold or given out. 

I do not really get what is meant by:
> If the specific Firefox OS device uses this service depends on a number of factors including which chipset is used in the device, which manufacturer built the device and via what partner and channel it was sold or given out.

If a specific FF OS device depends on \<listing of some specific features/properties\> it was sold? What has this to do with Mozilla Stumber?

**Comment by hannosch** [comment]
@rugk Mozilla Stumbler is our Android-only standalone application and has nothing to do with Firefox OS.

Some Firefox OS devices use the Mozilla Location Service (MLS, what this bugtracker is about) to query for location information. Most of them also use a GPS sensor in the device. The chipset, the manufacturer, the way the device was flashed all influence what combination of services and sensors is used to provide location information. Pretty much every imaginable combination of sensors and services is used in the devices out there:

* Only MLS, no GPS sensor
* MLS, a GPS sensor, a A-GPS service by a chipset vendor
* MLS, a GPS sensor, a A-GPS service by a third party
* MLS, a GPS sensor, no A-GPS service
* no cell/wifi location service, a GPS sensor, no A-GPS service
* no cell/wifi location service, GPS sensor, a A-GPS service by a chipset vendor
* a cell/wifi location service by a chipset vendor, a GPS sensor, a A-GPS service by a chipset vendor

The exact combination of services depends on many different factors, and there's no easy way to figure out which one any specific device actually uses. As a user you also cannot change any of this on an existing device.

Unrelated to all of this there is also support for actively stumbling on Firefox OS. FxStumbler is a prototype that hasn't seen any further development and shouldn't be used. Starting with Firefox OS 2.5 stumbling is built into the operating system itself.

**Comment by rugk** [comment]
Okay, thanks for the information. This is understandable.

Maybe you should rewrite this sentence on your website, so that everyone can understand it.

**Comment by hannosch** [comment]
I've chosen to remove the paragraph for Firefox OS instead, as the situation is even more complicated today with FxOS' shift to general connected devices. The homepage of this project isn't a good place to keep up-to-date information about this.
