### ISSUE TITLE
Cell Export File -> Field Unit contains value -1

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#475]
Description value unit:
For UMTS networks, this is the primary scrambling code (PSC). For LTE networks, this is the physical cell id (PCI). For GSM networks, this is empty. An integer, for example 312.

The export file contain many cellids where the field "unit" is -1.

**Comment by hannosch** [comment]
I've fixed this manually in the database and reset all psc values of -1 to null/none which gets output as an empty string in the export files.

The code was already correct and rejected any psc values outside the 0-511 range. So this was old data from the times when we used -1 to signal "unknown".

The next export files should all be correct.
