### ISSUE TITLE
Importing "MLS-full-cell-export" to db

### ISSUE THREAD

**Issue by imuneer** [mozilla/ichnaea#480]
Hi there,,

I am struggling to import the downloaded "MLS-full-cell-export-xxx.csv" file into my database. I have several tables starting with "cell_" and the fields on the CSV file does not completely matches to any of the table. In this case, how to I import the data from the the CSV to which table?

**Comment by hannosch** [comment]
We provide a custom import script to load the data. If you have a local installation you can run it via:
```
ICHNAEA_CFG=location.ini bin/location_load --datatype cell --filename MLS-full-cell-export-2016-01-12T000000.csv.gz
```
It'll read the database connection information out of the location.ini file you point it to via the environment variable. The datatype can also be ocid, if you want to import the export files from the opencellid project into the cell_ocid table.

**Comment by hannosch** [comment]
I've documented the command line tool in 343aa0d8d59354963b23ef76580d8a0da70a044d, which shows up at https://mozilla.github.io/ichnaea/import_export.html#import

**Comment by atilasoft** [comment]
Hi,

Where is "location_load" tool ?

Regards.
