### ISSUE TITLE
LTE and GSM cells missing from recent exports

### ISSUE THREAD

**Issue by kreed** [mozilla/ichnaea#481]
It looks like sometime between Jan 14th and now everything except UMTS cells went missing from the exports.
```
# zgrep -E '(LTE|GSM)' MLS-full-cell-export-2016-01-14T000000.csv.gz | wc -l
8762598
# zgrep -E '(LTE|GSM)' MLS-full-cell-export-2016-01-21T000000.csv.gz | wc -l
0
# du -hs MLS-full-cell-export-2016-01-14T000000.csv.gz MLS-full-cell-export-2016-01-21T000000.csv.gz
435M    MLS-full-cell-export-2016-01-14T000000.csv.gz
246M    MLS-full-cell-export-2016-01-21T000000.csv.gz
```

**Comment by hannosch** [comment]
Indeed, that's a new bug.

With the last software update we internally split the cell data into three different database tables, one for each radio type. The export code should merge the data from all three tables back into one file, but apparently that goes wrong.

I'll have a look at this.

**Comment by hannosch** [comment]
Duh, this looks like it was a fairly stupid bug :(

**Comment by kreed** [comment]
Wow, quick response! Thanks.

**Comment by hannosch** [comment]
Thanks for the report. I've patched this in the production system and the latest diff file has all three radio types again (MLS-diff-cell-export-2016-01-21T230000.csv.gz).
