### ISSUE TITLE
How fast my stumbled data gets to work?

### ISSUE THREAD

**Issue by Dinamitrij** [mozilla/ichnaea#482]
Hello All!

Recently, I've started stumbling data for MLS.
(Looks like I'm the only app-powered stumbler here in Riga, Latvia)

So, first of all, what's the meaning of the following Mozilla Stumbler screenshot? 
See:
![Screenshot](http://screenspic.appspot.com/pic?gid=agxzfnNjcmVlbnNwaWNyFQsSDFVwbG9hZGVkRmlsZRjZ1O0CDA)

Does it mean MLS has absolutely NO data for this region?!
The actual coordinates was the following:
https://www.google.com/maps/place/56%C2%B056'33.3%22N+24%C2%B006'45.4%22E/@56.942571,24.110408,17z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0

Actually, I was here 2-3 days ago, and still the MLS coordinates are missing for this place.
(all the grey lines lead us to the default point in the center of the city)

So, the question is - how fast my just stumbled coordinates (via Android Mozilla Stumbler app ) 
will be used by MLS to determine the particular device location?

**Comment by hannosch** [comment]
I'll answer this on the mailing list.
