### ISSUE TITLE
Error: image mozilla-ichnaea/redis not found

### ISSUE THREAD

**Issue by hieupm37** [mozilla/ichnaea#485]
When I run `docker-compose up -d`, I have this error message. 

```
Pulling redis (mozilla-ichnaea/redis:latest)...
Pulling repository docker.io/mozilla-ichnaea/redis
ERROR: Error: image mozilla-ichnaea/redis not found
```

How can I fix this error?

**Comment by hannosch** [comment]
Did you run `make` yet? The default make step takes care of initializing a whole lot of the environment, among those is building those two docker images. The make step responsible for this is `docker-images`.

If this works, the docs at https://mozilla.github.io/ichnaea/development.html are wrong. They say to run `docker-compose up -d` before running make.

**Comment by hieupm37** [comment]
That's right. Run `make` first fixes this problem, so the docs are wrong. Thank you.
