### ISSUE TITLE
Cellids with 1 sample and range=0

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#487]
Is it possible to block cellids with 1 sample and range=0 for example if
last_seen is > 360 days and don't export the cellids to the file?
The most cellids with 1 sample are wrong mayflies.

**Comment by hannosch** [comment]
I'm not sure if excluding these cellids from the download file is the right approach. There is some value in knowing what are possibly bogus cellids and have others look and analyze those. Once we hide them from the export, others can't do that anymore.

In our own query logic, we give each cell network a score, where things like last update time and sample count go into it, so these cellids won't be used if we have any better information.

**Comment by Gitschubser** [comment]
I understand but is it possible to hide the cells from the export for example, if the cellid
has 1 sample and range is 0 and
last updated > 600 days and
last_seen is > 600 days and
MCC is 2xx - Europe (keep cells from Africa in the export file because there are not many "stumbler" in the area).

Add the cellid to the export file if
last_seen is < 600 days or
more than 1 samples.

**Comment by hannosch** [comment]
With #490 I removed all cells which weren't modified in the last year from the export. I think that covers most of the wrong cells. The other remaining source of many bad cells is #340 (mnc 35/45/85 etc.).
