### ISSUE TITLE
Country Extracts

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#488]
The export file is very big.
Is it possble to add daily (or if changes exist) country extracts (country cell export)?

Example radiocells:
https://radiocells.org/downloads

**Comment by hannosch** [comment]
This would be an interesting feature. It currently takes more than an hour to dump the daily full export to a file. Splitting this up by country and than at the end combining the files would be a way to avoid the long running task.

I'd probably only do daily per country extracts without the differential files, as those per country files should be small enough to download them repeatedly.

**Comment by Gitschubser** [comment]
Good idea.

**Comment by jidanni** [comment]
Reading https://ichnaea.readthedocs.io/en/latest/import_export.html#data-export
and https://location.services.mozilla.com/downloads
it appears the data is only targeted at corporate users:
only entire world database available.
No way for individuals (who have been contributing data for years) to
say download the data for a 10 km. radius around a given lat/lon of their home town.

**Comment by jwhitlock** [comment]
@jidanni that sounds like a different feature request. Please open a new issue to discuss.

**Comment by jidanni** [comment]
Well I also opened https://github.com/mozilla/MozStumbler/issues/1870 .
There are many ways to contribute, e.g., also https://github.com/zamojski/TowerCollector/ ,
but when it comes time to even check if say that trip to grandma's house last one uploaded
sometime last week ever made it into the database. Well "you'll just have to download the
entire database or daily diffs."

**Comment by jidanni** [comment]
Another idea might be simply add the interface of
https://github.com/openbmap/radiocells-scanner-android
to the database. I find it much nicer than that of
https://www.opencellid.org/
