### ISSUE TITLE
Suggest wrong cellids to extinction 

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#489]
Is it possible to integrate an interface to delete incorrect cellids from the database for experts?
I would like to suggest false cellids from my provider for deletion. 
Keyword quality rather than quantity.
My provider contains more than 20 percent wrong cellids.

**Comment by hannosch** [comment]
What do you mean by incorrect? Are they at the wrong position, do they have half-correct cellids (wrong radio type, wrong wcdma cid) or are they no longer in service?

Generally we don't delete any records, but internally maintain a blocklist date and count for each cell network. If a cell network is reported in too many different locations over time, the block count will increase until we will consider the network permanently blocked.

It's another issue, if there are certain patterns we can use to identify wrong cell ids. If we can identify them as outright wrong, we can add those filters into the code and delete or correct networks outright.

**Comment by Gitschubser** [comment]
Source: MLS-full-cell-export-2016-05-13T000000.csv

- Wrong mnc only in germany: 
Example with mnc 25, 35, 45 and 85.
262-25: 41394 cells
262-35: 38352 cells
262-45: 34841 cells
262-85: 39063 cells
153650 cells with wrong mnc in germany.

- Wrong radio type (Cellid exist with radio type GSM and UMTS oder UMTS and LTE)
Example 262-1 T-Mobile Germany:
Cellid GSM: 1-5 digits
Cellid UMTS: 6-7 digits
Cellid LTE: 8 digits
31014 cells with a wrong radio type (mcc=262 and mnc= 1)
304198 cells and 31014 wrong cells = ~ 10 percent cells with wrong radio type (mcc=262 and mnc= 1)

- Wrong cellid 2147483647 in Germany:
373 cells

- Wrong LAC
Cellid with wrong LAC (1 cellid with the same radio type and another LAC)
LAC from another mnc (MNC 2 has a LAC from MNC 3)

- No longer in service
LAC change to a new LAC
Cellid change to a new cellid
RNC (UMTS) change to a new RNC
