### ISSUE TITLE
Comply with french privacy laws

### ISSUE THREAD

**Issue by ametaireau** [mozilla/ichnaea#49]
To comply with french rules, we would have to:

- Declare the database to the (CNIL)[https://en.wikipedia.org/wiki/CNIL]
- Provide a page, in french, explaining about this data retrieval, and how to ask for removal of such data
- CNIL asks that the collected data does not remain stored for more than 5 years.

http://www.cnil.fr/linstitution/actualite/article/article/geolocalisation-et-collecte-dinformations-issues-des-points-dacces-wi-fi-les-regles-a-respec/

Also, is github the right place to have these discussions or do we have a bugzilla space for this project as well?

**Comment by hannosch** [comment]
I've moved this over to a legal bug in bugzilla at https://bugzilla.mozilla.org/show_bug.cgi?id=1196228.
