### ISSUE TITLE
Block cellids where "Updated: 2014-08-19Txx:xx:xx.xxxZ"

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#490]
Is it possible to block the old cellids where the timestamp "Updated"  is the day 2014-08-19T (if updated and last_seen is 2014-08-19T)?

**Comment by hannosch** [comment]
Is there a specific reason to block that day in particular? Or do you want to exclude cellids if they haven't been seen or modified in a long enough time, maybe say 2 years?

**Comment by Gitschubser** [comment]
I see so much false cellids (wrong radio type, mnc, lac or cellid) in my area with this timestamp (it is the first possible timestamp "Updated" that you can see for all cellids).
I want to exclude cellids if they haven' t been seen or modified in a long enough time.

**Comment by hannosch** [comment]
I implemented this now, filtering out all cells from the full export, which weren't modified / last_seen in the past 12 months.

This filters out about 10% of the data, and all of the cells from the very beginning. Not quite sure yet when we get this deployed.

**Comment by hannosch** [comment]
This was finally deployed yesterday. The full download file is went down from 580mb to 480mb.
