### ISSUE TITLE
Statistics Wifi Networks

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#493]
Is there a problem with the statistics?

**Comment by hannosch** [comment]
No. We started removing some old and stale data from the database and adjusting the statistics accordingly. As a result we removed close to 100 million WiFi networks from the database. Those were networks which had only been seen a single time and that time was more than a year ago. We've also removed cell networks with the same criteria, but we haven't adjusted the stats for that yet. We'll look through the data a bit more and remove other outdated networks.
