### ISSUE TITLE
Use psc field for gsm channel

### ISSUE THREAD

**Issue by kolesar-andras** [mozilla/ichnaea#499]
API documentation says for **psc** field:

> The primary scrambling code for WCDMA and physical cell id for LTE.

I suggest to use this field also for GSM observations. Broadcast control channel (BCCH) is similar to PSC/PCI:

* only one base station can use at a place
* there are far less channels than base stations, therefore they should be reused
* potential usage of this field is similar: examine channel reuse
* number of available channels are similar

LTE AND WCDMA have 512 channels from 0-511, GSM has 548 channels three ranges:

* 0-124 GSM 900
* 512-885 DCS 1800
* 975-1023 E-GSM 900

A few devices report BCCH for GSM. I have a lot of measurements with this value and I would include this value in uploaded data using the psc field. Can I do it?

**Comment by hannosch** [comment]
The information we take in is in large parts based on what you can get on an Android device, as a normal application.

I haven't looked at the Android API docs in a while, but it seems there are two new additions to the CellInfo objects, specifically [CellInfoGsm](https://developer.android.com/reference/android/telephony/CellInfoGsm.html)/[CellIdentityGsm](https://developer.android.com/reference/android/telephony/CellIdentityGsm.html#getBsic()):

> getArfcn -- 16-bit GSM Absolute RF Channel Number, Integer.MAX_VALUE if unknown 
> getBsic -- 6-bit Base Station Identity Code, Integer.MAX_VALUE if unknown

Are those related to the BCCH, or do you know of an Android API which exposes BCCH?

Right now we have a fairly stringent schema, so values submitted in the psc field for GSM cells would just get thrown away.

**Comment by kolesar-andras** [comment]
Wow, it's great that Android API supports these values. GSM channels such BCCH are referred as [ARFCN](https://en.wikipedia.org/wiki/Absolute_radio-frequency_channel_number) (absolute radio-frequency channel number). getArfcn function just responds with BCCH channel (frequency) in GSM.

Names differ because every channel has a frequency and therefore an ARFCN. There are [several channels](https://en.wikipedia.org/wiki/Control_channel) in GSM and BCCH is only one from them. This is the channel which we can listen for broadcasts of a base station.

BSIC is a different thing. I have logged BSIC as well but I'm not sure if it is important enough. Is someone interested in it?

Can I ask you to store BCCH if supplied as an ARFCN for GSM measurements in psc field?

**Comment by kolesar-andras** [comment]
It seems frequency is available for all kind of cells (2G/3G/4G):

* [CellIdentityGsm](https://developer.android.com/reference/android/telephony/CellIdentityGsm.html).[getArfcn()](https://developer.android.com/reference/android/telephony/CellIdentityGsm.html#getArfcn())
* [CellIdentityWcdma](https://developer.android.com/reference/android/telephony/CellIdentityWcdma.html).[getUarfcn()](https://developer.android.com/reference/android/telephony/CellIdentityWcdma.html#getUarfcn())
* [CellIdentityLte](https://developer.android.com/reference/android/telephony/CellIdentityLte.html).[getEarfcn()](https://developer.android.com/reference/android/telephony/CellIdentityLte.html#getEarfcn())

This situation could be handled in a different way, more general than I have suggested yesterday. Cells have ARFCN in all three radio access technologies, this could be a new field named `arfcn`.

The existsing `psc` field could store `bsic` for GSM networks.

**Comment by hannosch** [comment]
One thing to note here is that while these APIs are available now, they are only available in API level 24 and later, which corresponds to Android 7.0. Currently about 1% of all users have a that Android version installed (source: https://developer.android.com/about/dashboards/index.html). As an added obstacle, while the API spec says these values should be supported, it doesn't mean they actually are on any given device. I've seen plenty of phones, which don't get updated modem firmware or an updated radio interface layer, so they simply report nothing for new APIs.

**Comment by hannosch** [comment]
Thinking about this from a different angle, I'm hesitant to add any new fields, which aren't clearly required or useful to aid in our primary geolocation use-case.

We added the psc field for WCDMA/UMTS, because in that specific case most phones only report a full cell identifier (mcc/mnc/lac/cid) for the currently active and connected cell network. For neighboring cell networks often only a mcc/mnc/psc combination is available. The idea (#17) was to use these incomplete identifiers and look them up based on their psc value and their proximity to the active cell. But that work never actually happened, so currently the psc values are unused. For LTE this kind of problem usually doesn't exist, but we added the physical cell id under the same key just the same.

For GSM networks this doesn't apply as you typically don't see any neighboring cell networks at all, but the phone only reports the full cell identifier for the active cell network.

**Comment by kolesar-andras** [comment]
Before summer of 2016 I had similar experience from several Samsung devices. Then I have asked my friends and colleagues about their phones. A new world have opened for me. I have learned about LG phones:

* report PSC (Samsungs did not)
* report neighbouring GSM cells (Samsungs did not report any neighbours)
* do not stop reporting cell changes when screen is off (unlike newer Samsungs)
* have lower power consumption with GPS on (whole day vs a few hours)
* have "LTE only" setting in service menu

Later I have found cheap chinese Doogee phones that extended the above list with:

* have two sim slots (one 4G and one 2G modem)
* reports neighbouring WCDMA cells
* have even lower consumption GPS receiver with better accuracy
* much larger battery (4000 mAh runs 48 hours with GPS always on)
* bands can be filtered in service menu and setting is remembered on reboot

Measurements from these phones do not need any algorithm to look up incomplete identifiers as neighboring cells have full records (mcc, mnc, lac, cid).

There are possibilities to get data directly from modem, even those are not supported by Android API. I log GSM bcch+bsic and WCDMA psc+channel for neighbouring cells with Samsung Galaxy S2 running a custom application. I also have Nokia phones running Netmonitor, a Raspberry Pi collects data from them. Android API limits do not apply for these methods.

I use PSC to find related station identifiers, see #501. Frequencies help to understand the role of cell identifiers in the network. For example when more than 3 WCDMA cells belong to a base station (6 or 9) they usually use the same psc for same directions but a different frequency band. There can be even 12 cells where fourth round uses 900 MHz WCDMA band.

Because same PSC is used on different bands you can't lookup cell identifier by psc if you dont't know the frequency. However, you don't need to know cell id exactly if the fallback suggested in #501 would give a match based on station identifier even when cell id is not the same.

Similar calculation can be done on GSM networks where BCCH (or BCCH+BSIC) is known for neighbours but phone did not report cell id. Here BSIC helps to identify cell if BCCH is ambiguous.

Frequency is also related with coverage area therefore it's important to know from what distances can we expect to receive a particular cell from base station.
