### ISSUE TITLE
Import sample data

### ISSUE THREAD

**Issue by Alixpat** [mozilla/ichnaea#503]
Hi,

How should I do to import a sample data ?

Regards.

**Comment by Manicben** [comment]
Regarding this issue, would it be possible to get an explanation of the MySQL database table columns in the meantime?

I've been loading CSVs manually from https://www.mylnikov.org/download into my own hosted Ichnaea instance. In order to make this work I ensured that the columns matched, however I didn't understand why there was a separate 'cellid' and 'cid' column. Afterwards I found out that 'cellid' was a binary field and due to being the primary key, served as some kind of lookup key during request queries.

None of this is covered in the current documentation on Ichnaea, so I was hoping to get a response here if possible. Of course, adding some method of importing data (in CSV format) to Ichnaea would be very helpful in future too.

**Comment by hannosch** [comment]
Currently the 2.x version has no import script, it will get added back in the future again. If one needs to load cell data into this version, the old script from the 1.5 branch (https://github.com/mozilla/ichnaea/commit/5d58e93eedcd25f12b457709b888498af790ec25#diff-a223b4aea91068919bd1660253a87b0d) might help to explain the mapping of CSV fields to database columns.

The most important part is constructing the right primary key, as a binary field combining the radio, mcc, mnc, lac and cid values into one cellid column. The encode_cellid function and the CELLID_STRUCT (https://github.com/mozilla/ichnaea/blob/master/ichnaea/models/cell.py#L296) should give hints as to how to do that.

**Comment by willkg** [comment]
I'm adjusting the scope of this to "write tools for generating sample data for a local dev environment". I'm not sure what other use cases there are for sample data other than development. If there are other use cases, we can defer those to new issues.

My goal is to build enough sample data that we can test and debug the major features of ichnaea and write a basic system test:

* locate lookup api
* region lookup api
* geosubmit api
* internal export
* public cell export to the downloads page

There's a ton of details in those APIs, so I think I'll do a basic set of sample data for this issue that covers some things and we can improve that via future issues and pull requests as needs come up.

I'm going to add a cli to add/manipulate data in the `api_key` table. That seems pretty critical to testing API endpoints.

The base migration creates an "internal" export in the `export_config` table which covers the internal export. After we add an s3-equivalent, we should add a "bucket" export, too. At some point, maybe a "geosubmit" export, but that probably requires a dummy ichnaea service. Some day.

I think that leaves these populating these tables with data:

* blue_shard_N
* cell_area
* cell_gsm
* cell_lte
* cell_wcdma
* datamap_ne
* datamap_nw
* datamap_se
* datamap_sw
* region_stat
* stat
* wifi_shard_N

I'll work on that.

**Comment by willkg** [comment]
For `cell_area`, `cell_gsm`, `cell_lte`, and `cell_wcdma`, maybe we can write a script that grabs the most recent Differential Cell Exports from the prod downloads page and inserts that data?

Seems like `datamap_*` tables get populated by `update_datamap` tasks. Maybe we can write a script that runs those tasks?

**Comment by willkg** [comment]
@jwhitlock and I talked. He's going to try tackling building an "import" command for the exports you can download from the MLS downloads page: https://location.services.mozilla.com/downloads

**Comment by willkg** [comment]
We landed the `load_cell_data.py` script that pulls in cell data.

It's probably the case we still want bluetooth and wifi data, but we're going to push that off to another milestone.

**Comment by jwhitlock** [comment]
The MAC Address has a bit that specifies [Universal vs Local](https://en.wikipedia.org/wiki/MAC_address#Universal_vs._local) addresses. A sample data generator could create some local MAC Addresses for testing purposes on dev, assigned to locations of Mozilla offices.
