### ISSUE TITLE
Telefonica Germany: Consolidation completed, Mobile Network Code 262-07 disappeared

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#509]
Telefonica Germany has completely changed the Mobile Network Code to 262-03.
Mobile Network Code 262-07 has disappeared.
Does it make sense to clean up the database for Mobile Network Code 262-07?

https://www.teltarif.de/o2-e-plus-telefonica-netzcode/news/69327.html

**Comment by hannosch** [comment]
Thanks for the note.

Unfortunately I no longer have access to the database itself and can't simply delete data out of it anymore. In principal I agree that in this case, deleting the data outright would be the sensible thing to do.

I always meant to add some kind of automated cleanup logic, which would remove data if it hasn't been seen anymore in 1 or 2 years. That kind of approach would eventually take care of this, but alas I never got around to it.
