### ISSUE TITLE
Invalid data easily comes in as routers have multiple antennas

### ISSUE THREAD

**Issue by crankycoder** [mozilla/ichnaea#510]
From IRC (user la|r|ma):

I managed to pollute the mls database with wrong data only by doing geolocate queries, is that intended?

To be more precise: I recently moved from one location to another, taking my wifi router with me. I use the UnifiedNlp backend which does geolocate queries every now and then. After moving, geolocate still located me at my old home (not a surprise), but apparently the mls database used this as an indicator to also set the location of the APs of my new neighbors to my old home. Now, after changing the mac address of my old AP, MLS still defines my location to be my old home.

I guess you require at least 2 mac addresses to use geolocate, but modern routers do 2.4G and 5G wifi, thus share two mac addresses.

**Comment by crankycoder** [comment]
I think we only apply the 2 MAC address requirement on geolocate operations, but don't do anything for inbound data.  

I'm not entirely sure how badly adding a multiple MAC address requirement for submissions will affect data collection.  I imagine in most urban areas - we shouldn't be impacted much at all.

**Comment by jwhitlock** [comment]
Structured logging now includes the number of WiFi stations provided, so we can more directly answer what would happen if we raised the requirement from at least 2 WiFi to higher. There may be other ways to deal with this issue.
