### ISSUE TITLE
Continuously getting a "Access denied for user 'root'@'172.17.0.1' (using password: YES)"

### ISSUE THREAD

**Issue by gnaazr95** [mozilla/ichnaea#511]
Hi,

I'm continuously getting the error mentioned in the title. I'm currently following this documentation: https://mozilla.github.io/ichnaea/install/deploy.html and am stuck on the step where I have to run this command "docker run -it --rm --env-file env.txt 
mozilla/location:2.1.0 alembic stamp base"

This is where I am getting the Access denied error. I have both docker and docker-compose set up, when I run docker-compose ps I get the following outout:

Name Command State Ports

name_db_1 docker-entrypoint.sh mysqld Up 0.0.0.0:3306->3306/tcp

My docker-compose.yml file looks like this:

db:
image: mysql:5.7
ports:
- "3306:3306"
environment:
- MYSQL_ROOT_PASSWORD="password"
- MYSQL_USER="root"
- MYSQL_PASSWORD="password"
- MYSQL_DATABASE="name_db_1"

And this is the env.txt that I am calling on:

DB_HOST=172.17.0.1
DB_USER=root
DB_PASSWORD=password
GEOIP_PATH=/app/geoip/GeoLite2-City.mmdb
REDIS_HOST=localhost

I have set up the privileges on the database also. When I login into the database and run SHOW GRANTS FOR 'root'@'172.17.0.1' I get the following output:

+----------------------------------------------------------------------+
| Grants for root@172.17.0.1 |
+----------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON . TO 'root'@'172.17.0.1' WITH GRANT OPTION |
+----------------------------------------------------------------------+
1 row in set (0.00 sec)

I also get this when I check the grants for 'root'@'%':

+----------------------------------------------------------------------+
| Grants for root@% |
+----------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON . TO 'root'@'%' WITH GRANT OPTION |
+----------------------------------------------------------------------+
1 row in set (0.00 sec)

Any ideas as to what may be going wrong? I've been stuck on this for quite some time...

**Comment by hannosch** [comment]
In the docs it says to name the database ‘location’. See also https://github.com/mozilla/ichnaea/blob/master/docker/mysql/Dockerfile

You specified something different via ‘MYSQL_DATABASE="name_db_1"’.

**Comment by gnaazr95** [comment]
I see, I actually got the service to work when installing the development version of the service previously but had all that data deleted some time back. Did going through the development version of the esrvice setup MYSQL,Docker, Redis etc for me? Just a little confused as to what the difference was between going the development version route vs production version route.
