### ISSUE TITLE
Get wrong location from the service /v1/geolocate

### ISSUE THREAD

**Issue by jauhenk** [mozilla/ichnaea#513]
Hi guys! The user's location is "La Roquette sur Siagne" (is a village in East of France), however the location which I got is shown as "La Rochelle" (western France, { location: { lat: 46.1571002, lng: -1.1565899 }, accuracy: 10 }).
Please let me know if I also should provide the list of wifis.
Thanks!

**Comment by jwhitlock** [comment]
@jauhenk I imagine you have given up on this issue in the last three years!

If not, the way to fix this is to use the [geosubmit API](https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html). It takes similar data to the [geolocate API](https://ichnaea.readthedocs.io/en/latest/api/geolocate.html), but also accepts a ``position`` with the latitude and longitude. This will help train the station database for the correct position for these WiFi access points.

Not everyone can use APIs directly like this. I wish I could recommend a client instead, but there are none I can recommend at this time.

**Comment by jwhitlock** [comment]
Please re-open as needed.
