### ISSUE TITLE
Can you explain in the documentation how speed up the call method of the worker ?

### ISSUE THREAD

**Issue by Adaok** [mozilla/ichnaea#515]
Hello,

I'm working on ichnaea solution and I need to speed up the call of worker container in data/export.py,  i want to chec quickly if geosubmits sent are handled.
But it's so long  !!!
I have send geosubmit there is already 20 minutes of that and I have the same : 
`WARNING/PoolWorker-1] data.export.py IncomingQueue __call__, monitor queue`

I can't find distincly were this params can be changed, can you explain me please ?

Thanks in advance.

**Comment by chrisail** [comment]
Hi Adaok.

Have a look at ichnaea/ichnaea/data/tasks.py and modify @celery_app.task '_schedule' property.
