### ISSUE TITLE
Use Ichnaea as default location service without Android root access?

### ISSUE THREAD

**Issue by madb1lly** [mozilla/ichnaea#517]
Hi all,
I think I'm asking for the impossible here, but can MLS be used as the default location service in Android without root access? Unfortunately there's no root solution for my phone yet.
Cheers,

**Comment by cpeterso** [comment]
The [microG project](https://microg.org/) has some code to support the MLS (Ichnaea) as a system location service, but I've never used it:

https://github.com/microg/IchnaeaNlpBackend

**Comment by madb1lly** [comment]
Thanks. I did already try that but it didn't work. I looked again and I see that it now needs uses xposed, so I may try it again, although it requires busybox be installed too.
