### ISSUE TITLE
Problem with installing mysql-connector

### ISSUE THREAD

**Issue by haiyanghe** [mozilla/ichnaea#518]
At the moment only mysql-connector 2.1.6 is available via pip.

In requirements/binary.txt mysql-connector is set as 2.2.3

**Comment by Havenriley** [comment]
Thank you so much. I will hope to back to it tomorrow

**Comment by lonnen** [comment]
I believe this is now resolved:  https://github.com/mozilla/ichnaea/commit/b8c23935e968101ad7f5dd6d66dddedab42e190d
