### ISSUE TITLE
Unverifiable hash in iso8601

### ISSUE THREAD

**Issue by haiyanghe** [mozilla/ichnaea#519]
Unverifiable hash in requirements/all.txt for iso8601==0.1.12.

**Comment by jwhitlock** [comment]
We've move ``iso8601`` to ``requirements/constraints.txt``, and we're using ``hashin`` to populate the hashes of all the downloads, not just the one used in the docker container:

https://github.com/mozilla/ichnaea/blob/71b39befdd6d618d05fc179077cc40c904137437/requirements/constraints.txt#L157-L160
