### ISSUE TITLE
Quote choice fields

### ISSUE THREAD

**Issue by jidanni** [mozilla/ichnaea#524]
In https://github.com/mozilla/ichnaea/blob/master/docs/api/geosubmit2.rst
```
radioType
The type of radio network. One of gsm, wcdma or lte.
...
locationAreaCode
The location area code for GSM and WCDMA networks. The tracking area code for LTE networks.
```
I would say
```
radioType
The type of radio network. One of "gsm", "wcdma" or "lte".
```
Else on cannot be sure if you really want them in lower case, or if the author just didn't press the SHIFT button when typing that paragraph.

**Comment by jwhitlock** [comment]
After the documentation overhaul in #925, these are now displayed in fixed-width text on https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html#cell-tower-fields making it clearer that these are the exact values.
