### ISSUE TITLE
add 5g support/prepare for 5g support

### ISSUE THREAD

**Issue by Djfe** [mozilla/ichnaea#525]
the 5g spec and similar stuff have been published some months ago.
Since the first devices might ship in 2019 already, you might wanna prepare support for 5g in the database, api etc. over the next months or so.
Just so you're prepared, so that adding actual support (when the time comes) on real Android devices that ship with it will be a piece of cake :)

this just a friendly reminder that the standard is on it's way. I don't want to put any pressure on it, there is still plenty of time. That's why I opened this issue this early.

**Comment by tuxayo** [comment]
What would be the impact of 5g on ichnaea/MLS?

How does this affect data collection and MLS querying?

**Comment by Djfe** [comment]
for one: the stats on the MLS web page have no entry for 5g cells
and secondly the IDs for cell towers might work differently in the 5g standard (I haven't read the standard)

there might be further problems, I haven't read the standard so I don't know

**Comment by Djfe** [comment]
Vodafone Germany rolled out 5g last month.
https://www.vodafone.de/featured/inside-vodafone/5g-handy-netz-von-vodafone-ab-morgen-auf-deinem-smartphone/

There is still no entry on here:
https://location.services.mozilla.com/stats/regions

are we able to collect data from such cells on smartphones like the Huawei Mate 20 X 5G or the Samsung Galaxy S10 5G.

Would this cause errors in mozstumbler -> ergo in the Firefox for Android implementation on these devices?

**Comment by zamojski** [comment]
I'm interested in contribution using [Tower Collector](https://github.com/zamojski/TowerCollector/) application. Can you please share the timeline of implementation?

**Comment by willkg** [comment]
We have no ETA for when one of us will look into this. We're focused on other things at the moment. If someone else wants to look into this and submit a PR, that'd be super!

**Comment by zamojski** [comment]
Tower Collector is ready for uploading 5G and TD-SCDMA cells. I just need to know how the API will look like from MLS side.

**Comment by zamojski** [comment]
Is there any chance to get 5G and TD-SCDMA support by the end of this year? I'm not a Python programmer but it doesn't seem to be rocket since to implement support for 2 more networks. This issue is already around 1.5 year old and to me it looks like nobody maintains MLS anymore.

**Comment by jwhitlock** [comment]
The next steps are:

* Research the identifiers for the new station types
* Determine or guess at parameters like signal strength min, max, and average
* Plan for database storage of new radio types

We don't have domain experience with cell radios on the team, which makes it difficult to predict how long it will take to complete the research tasks.

**Comment by zamojski** [comment]
I'm not a radio expert but I would personally start from taking a look on Android definition of [5G cell](https://developer.android.com/reference/android/telephony/CellIdentityNr), [5G signal](https://developer.android.com/reference/android/telephony/CellSignalStrengthNr), [TD-SCDMA cell](https://developer.android.com/reference/android/telephony/CellIdentityTdscdma) and [TD-SCDMA signal](https://developer.android.com/reference/android/telephony/CellSignalStrengthTdscdma). They must not be far away from the technical standard.

**Comment by gopi-ar** [comment]
We just finished adding support for 5G to [OCID](http://wiki.opencellid.org/) after @zamojski reached out to us at Unwired. If MLS ever adds support for 5G (NR) and NBIoT, please consider using `NR` and `NBIOT` as the new radio types. This will ensure OCID & MLS continue to share a common export format.

**Comment by TripEricson** [comment]
So what exactly is needed to make it possible to submit 5G-NR data to MLS and make it show in the download files going forward?  The data format is the same, just with larger integers in a few columns and "NR" as the radio type.  Given that simplicity, I'm not clear why Open Cell ID supports NR but MLS does not, especially now that most US T-Mobile customers are now often on 5G-NR standalone much of the time.  

I'm definitely not a programmer, but I'm glad to help if there's a way I can do so.
