### ISSUE TITLE
Migrate to CircleCI V2 config

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ichnaea#529]
I recently got an email from "The CircleCI Team" saying:

> Last month, we pointed you toward resources to help you migrate active projects from CircleCI 1.0 to 2.0 with the [Migration Center](http://go.circleci.com/Q0MH0GM0Zn2GW0k120044I0). 
>
> [With only 30 days left until CircleCI 1.0 sunsets](https://circleci.com/sunset1-0/), we want to ensure you have everything you need to help you with any active projects that still need to migrate to 2.0. Our team has been busy creating resources and new features to help make it easier:

More info in the CircleCI Blog at https://circleci.com/blog/sunsetting-1-0/ and https://circleci.com/docs/2.0/migration-intro/

I also found https://circleci.com/docs/2.0/local-cli/ which points to a handy CircleCI v2 config validator (using something like <kbd>$ circleci config validate -c .circleci/config.yml</kbd>).

**Comment by tigeratom59** [comment]
Thank

**Comment by willkg** [comment]
@jwhitlock is working on this now.

**Comment by jwhitlock** [comment]
The master branch runs on CircleCI 2.0 now, with PR #821 and PR #823.
