### ISSUE TITLE
Blocked in Russia

### ISSUE THREAD

**Issue by 532910** [mozilla/ichnaea#620]
http://isitblockedinrussia.com/?host=location.services.mozilla.com

**Comment by c-e-p-x-u-o** [comment]
Unable to find location.services.mozilla.com and 34.255.82.141, 34.252.164.43, 34.251.59.153 records in russian blacklist. Moreover it doesn't look like russia blacklist.

**Comment by Djfe** [comment]
Not anymore :) (just checked it out of curiosity)
