### ISSUE TITLE
Automate map tiles generation

### ISSUE THREAD

**Issue by hannosch** [mozilla/ichnaea#67]
As part of the new map (#33) we create png map tiles. This is currently a manual process based on the steps at https://gist.github.com/hannosch/0b80b01d260cc2d41957 or the map.sh script that currently exists only on the server  (the last step in the gist is optional, as we don't use a proper tile server yet, but just let nginx serve a nested directory tree).

This process is not documented, not checked into source control and generally an ad-hoc hack. We should make it better (tm).

Things to investigate:
- How to install the datamaps tools (https://github.com/ericfischer/datamaps); create an rpm (needs a very recent libpng-dev)
- Where to store the resulting pngs? Currently on local VM disk. Should be on something that's shared by all machines.
- Where and how to run/monitor this? It should be a scheduled task, but celery is ill-suited for this, as it runs for maybe an hour on a 8-core machine.
- Use a different domain name, like tiles.location.services.mozilla.com for it? ckolos might be able to get us an alias for that quickly.
- The pngquant (or optipng / pngcrush) step is optional, but a nice way to reduce file size. Investigate different options and see if it makes a difference / what settings apply to our image data.
- Investigate using a proper tile server with an mbtiles source (it's basically a sqlite db). Might be in conflict with putting this on a CDN / shared resource. Probably not worth it for the little data we have.
- Others...

**Comment by noname2534** [comment]
+1
