### ISSUE TITLE
docker-based local development environment

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#828]
With Socorro, Tecken, and Buildhub2, we were able to get a complete local development environment running with four or five commands (depending on what you were doing). This was based on make, git, docker, and docker-compose. It covered building images, initializing services, and fetching any initial data. It made it much easier to do development because we could throw away environments and start over trivially.

Properties I'd like in a local dev environment:

1. easy-to-document "getting started" for a local dev environment
2. easy to throw away all state and start over
3. easy to script environment building and testing

This issue covers getting a local dev environment set up for Ichnaea with similar properties.

**Comment by hannosch** [comment]
The dev script (https://mozilla.github.io/ichnaea/install/devel.html#code) should do most of those things. It gets you the docker-compose based containers, so you have mysql, redis and the three app containers running locally.

For a systems test, you could try to automate the steps mentioned in https://mozilla.github.io/ichnaea/install/debug.html as a start.

**Comment by willkg** [comment]
I think a lot of what I want is there already, but in a slightly different form. To make it easier for this team to do development, it's easier to make it consistent with past projects.

I'm going to grab this because I did Socorro and Antenna and have feelings about ergonomics. I'll list more specific changes I want to make after spending more time with what's there now.
