### ISSUE TITLE
[research] migrate to postgres

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#829]
The MySQL story here is pretty rough. This issue covers figuring out whether there's anything that requires us to use mysql over postgres and if not, figuring out the plan to rework things to switch to postgres.

**Comment by hannosch** [comment]
Off-memory, so I may be wrong: The project only uses MySQL over Postgres, as AWS was’t offering Postgres at the time. Currently there is one r/w (or master) db and a single read-only replica. The web frontend code only uses the replica, as it does no writes to the db, the celery backend worker only needs the r/w db.

In terms of db specific code, there shouldn’t really be all that much. Somewhere is a custom upsert implementation and there’s one place where the „rows changed“ return value of a query is used to figure out if rows got inserted and/or updated. MySQL counts one of those as 1 and the other as 2 rows.

Other than that the code is written in direct MySQL dialect in places, but most should use SQLAlchemy. Probably the alembic code for db schema migrations is the most dialect specific.

Almost all the actual queries are really simple primary key lookups. There are basically no foreign key relationships in the schema at all.

**Comment by willkg** [comment]
This helps a ton! We had similar issues with SUMO and Input and Socorro, so I can relate.

**Comment by willkg** [comment]
@jwhitlock and I talked about this. Everything we're seeing suggests this is a pretty involved project. We want to push this off until after GCP, so I'm bumping it out of the mielstone.
