### ISSUE TITLE
switch to markus for metrics

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#830]
Ichnaea sends metrics to Datadog using the datadog Python library. We're probably going to switch off of Datadog, so we'd need to rework metrics to use the statsd library.

There's some code in `ichnaea/log.py` to create a debug datadog client.

We should look at switching to using [Markus](https://markus.readthedocs.io/) which provides a convenient abstraction layer over metrics generation. That'll make it easier to switch from datadog to statsd in the future--it'll just be a configuration change.

**Comment by hannosch** [comment]
The metrics code relies heavily on tags for each metric. IIRC those are a datadog specific addition to statsd, so that might be an issue.

**Comment by willkg** [comment]
My bad--I misunderstood what we were doing. We're not switching to the statsd protocol--we're sticking with the datadog enhancements to statsd. So tags and all that should work fine going forward. Yay!

Still, I think switching to Markus has some value. It helped us a lot in development and testing with Socorro, Antenna, Buildhub2, and Tecken. It's got some niceties.
