### ISSUE TITLE
get travis ci working with ckolos/dammit branch

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#831]
We're currently deploying MLS from the ckolos/dammit branch. Travis CI is set up for that branch, but failing:

https://travis-ci.org/mozilla/ichnaea/builds/557384813

This covers getting Travis CI working for that branch.

**Comment by willkg** [comment]
@jwhitlock and I talked a bit about this. We can ditch Python 2.6 testing--that solves one failure. If we can get it passing with Python 2.7, that'd be great. If not, we should figure out another way to run the tests for changes made in this branch.

**Comment by jwhitlock** [comment]
Production is running Python 2.6, so we should keep testing that if possible.

**Comment by willkg** [comment]
Great googley moogely.

**Comment by jwhitlock** [comment]
This is working with #833, and is now switched to looking at 1.5.x. We need to test deployment from 1.5.x branch, but that feels like a different issue.
