### ISSUE TITLE
switch to everett for configuration

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#836]
Configuration in the master branch is defined in `ichnaea/webapp/config.py` using a bunch of `os.environ.get()` lines.

We should switch to a configuration library--that'd be easier. If we switch to everett, then we get free documentation.

This covers doing that.

**Comment by willkg** [comment]
https://everett.readthedocs.io/en/latest/

**Comment by hannosch** [comment]
OS environment variables were used, as that was easiest to provide to a docker container at runtime at the time. Originally the project had a `.ini` file with a ConfigParser based syntax.

**Comment by willkg** [comment]
While looking into this, we should review the configuration situation. What configuration exists? What's documented? What can we remove and/or adjust to improve things?
