### ISSUE TITLE
Remove exported data blobs

### ISSUE THREAD

**Issue by ckolos** [mozilla/ichnaea#838]
It would reduce the complexity of the infra if we were to remove the data exports functionality from our deployed MLS stack.

**Comment by willkg** [comment]
I'm not sure why MLS exports data. Do we know why it was implemented and what it's used by?

**Comment by hannosch** [comment]
The issue tracker is probably not the best place to discuss this. I'm not sure if the dev-geolocation mailing list is still used? I'll try to give some background:

The project started out with the idea of a federated system of multiple open data projects all sharing location data and building up a free and open alternative to the closed nature of the predominant location providers. There were multiple smaller projects at the time and OpenCellID as a major project. The public cell export data was developed in cooperation with OpenCellID as a means to share location data between the two projects. It also allowed anyone to run the ichnaea stack on their own and get access to at least the aggregated cell data. The underlying observations couldn't be shared, as there were license and privacy concerns. For Bluetooth and WiFi data the privacy concerns made it impossible to share even the aggregated data.

The original vision of a federated system never came to pass and Mozilla pulling out of the smartphone OS market meant that Mozilla had no direct consumer for this service anymore.

Whether or not the export data functionality should be removed, really depends on what the vision or purpose of this project is going to be. If all that remains is providing GeoIP-level country estimates for the search provider defaults lookup, than the ichnaea codebase should be abandoned and a new implementation for the minimal required API should be built.

**Comment by willkg** [comment]
I think removing data exports should be tied to removing the submission functionality. If we have stumbling, we really want a community around stumbling and that gets a lot harder if we don't  export data. I think the two are hand-in-hand.

Given that, I'm going to close this out because it's part of #839.
