### ISSUE TITLE
Do away with user-submitted data

### ISSUE THREAD

**Issue by ckolos** [mozilla/ichnaea#839]
Current lookup data suggests that while 60% of our location responses are served via local data source, the remaining 40% are served via GeoIP lookup from a third party DB locally installed on the host. Removing the ability to submit data to ichnaea (and subsequently process it) would eliminate a great deal of the infra needed to run ichnaea in production, including the DB required to store it as well as the workers needed to process incoming data.

**Comment by hannosch** [comment]
If you remove the user-submitted data side of the codebase, you are probably better off resurrecting https://github.com/mozilla/geodude or build a new service with the minimally required API.

**Comment by ckolos** [comment]
That's an excellent pointer... Thanks @hannosch!

**Comment by willkg** [comment]
We've had a few talks amongst the team about where we want to go with MLS--whether to stick with ichnaea or build a new geodude--and we've decided to stick with ichnaea for now.

While the stumbling and export features heavily affect the complexity of the code and infrastructure and that has consequences for us, I think we want to keep stumbling for a while longer. If it becomes clear that the stumbled data isn't helping geolocation lookup quality or the costs outweigh the value, then we'll probably switch MLS from ichnaea to a new codebase.

Given that, I'm going to close this out.
