### ISSUE TITLE
add an admin

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#846]
Currently, the way we manage API keys and investigate data in the db is manually on an admin node.

We're in the process of redoing the infrastructure and won't have access to admin nodes.

This issue covers looking into building out a web admin. Then we'll write up an issue for API key management requirements.

**Comment by hannosch** [comment]
The need for an admin web UI was never urgent enough, as I was the only real website admin and had production access. So it was easier to just pre-create 100 api keys, insert them into the database and than do all management in a Google spreadsheet. Totally low-key, but good enough at the time.

**Comment by willkg** [comment]
One thing we need to be wary of is that the webapp uses the ro db uri--it's read-only. The admin will need to be read/write.

It might make more sense to have the admin be a separate webapp that runs on a separate node on a different domain.

**Comment by willkg** [comment]
I tweaked the title to generalize a bit.

The new admin will be tied to the new infrastructure. However, if it turns out we need something sooner that works on the current infrastructure, I can throw together a one-file Python script cli.

**Comment by jwhitlock** [comment]
I created a duplicate, now closed, with this description:

Create a website for administering a Ichnaea instance. The first version would be restricted to maintaining the configuration tables ``api_key`` and ``export_config``. In Mozilla's production environment, it should use single-sign on and be restricted to core team members. It may use a known username and password in the development environment.

If I was creating it, I would use the Django admin, and create parallel Django models for the SQLAlchemy models for these two tables.

First proposed as part of [bug 1600845 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1600845#c4)
