### ISSUE TITLE
fix front page so it shows what MLS shows in local dev environment

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#847]
When you run the webapp in the lcoal dev environment, it shows an unhelpful "It works!" page. The code is in `ichnaea/content/views.py` and it looks like it's because `MAP_TILES_URL` and `MAP_TOKEN` aren't set.

This issue covers getting all that working so we have something to see in the local dev environment.

**Comment by hannosch** [comment]
This was done, so other people running an instance of ichnaea wouldn’t automatically get the Mozilla branded website. The codebase unfortunately includes both the generic location service implementation and the Mozilla specific MLS website bits. It was never a high enough priority to split those into two different repos and let the MLS repo pull in a version of the ichnaea code.

**Comment by willkg** [comment]
I fixed this in the local dev environment when I fixed the #853 . Closing this out.
