### ISSUE TITLE
[research] why is wifi data in sharded tables?

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#852]
Wifi data in the db is broken out into 16 tables labeled `wifi_shard_X` where X is a hex character.

This issue covers looking into why that is and whether we still need it.

**Comment by hannosch** [comment]
The cellular tables are also sharded, but using the cell standard (gsm, wcdma, lte) as a shard key. The Bluetooth side of the project never took off, as we got all data from a partnership and nothing from our own stumblers. But it was easiest to just use the same schema for Bluetooth.

While we were actively developing the code base, we frequently made changes to the DB schema, adding new columns, changing datatypes of columns or adding indices and some such.

We also knew we were going to get about 2 billion or so WiFi networks when we were successful.

The calculation on the one hand was: How big does the actual InnoDB database file per table get? One WiFi row is currently 100 bytes of data (ignoring the indices). Putting everything into a single table would be approximately 200GB of raw data. Divided by 16 we got 12.5GB. For purposes of backups, file system level file locking or something going wrong, we felt ~10gb was a saner size for a single file.

The other issue was the time it took to apply a DML change, like adding a column to an existing table. As you recently saw, it takes about 16 minutes to do a full table scan SQL query on one of the WiFi tables. Doing a DML statement like `add column` takes at least that long. With those times, you get long full table locks in MySQL and at some point above it, the DB replication fails. Both the r/w master is a Multi-Availability-Zone instance, so really 2 database kept in sync and than there's the ro-replica in addition.

I think MySQL might have gotten better with transactional and online DML in later versions, but in 5.7 it was still quite awful.

The shard key itself for the WiFi tables was chosen based on three factors: 1. It should get a roughly even distribution. 2. It should be simple to calculate just from the BSSID (mac). 3. It should preserve some locality.

The argument for the third factor was: It's fairly common for a single WiFi router from one vendor to expose 2 or more logical WiFi networks. Or in an office setting, there are often multiple networks from the same vendor around. The mac address is split into a 3 bytes vendor prefix and 3 bytes of a counter. By basing the shard key on a part of the vendor prefix, the chances are higher you are doing SQL queries later on, with lots of values coming from the same table. With a truly random key, you'd probably get 16 different SQL queries and all tables would always be involved (assuming you see at least 16 different WiFi networks around).

**Comment by willkg** [comment]
That's super helpful--thank you!

I think I want to close this out. We don't have the bandwidth to re-measure and re-think how the tables are structured and other than "can we simplify things?" there's no compelling reason to do so right now.
