### ISSUE TITLE
Exchange with OpenStreetMap (masts, traces, ...)

### ISSUE THREAD

**Issue by Matthias84** [mozilla/ichnaea#856]
Hi, I contribute to boths projects and would love to ask if you see a better cooperation / data exchange, too:

# Locations of basestations

OSM has a lot of radiocell masts and towers, (see [newcloudatlas.org](http://newcloudatlas.org) filtering) that could be used to get a better location of the antennas. In the other direction, OSM could get an data export with GSM cell antenna candidates, includion average location, opperator, first-last-seen, number of scans, area of scans, ...). That could be done via WMS to include it as background map to the OSM editor software and with GeoJSON export, to make it easy to copy & paste.

# GPS routes

The gps traces are essential to align aerial imagery, find new roads and to learn how fast and in which direction you can travel along a street. So if you could share the cronology of reports as WMS (lines indicating age, speed, wifi-density, ...) this would be great tool.

# Building locations

Most wifi locations are indoor. You could make use of OSM building outlines, to improve the accuracy where you think the router is located. This could work also in 3D.

**Comment by jwhitlock** [comment]
Thanks @Matthias84, these are interesting ideas. MLS introduced a [policy change in 2019](https://blog.mozilla.org/services/2019/09/03/a-new-policy-for-mozilla-location-service/), and we've limited our data collaboration with other projects. It may be a while (months to years) before we're in a position to start new collaborations.

The MLS [model of a station](https://ichnaea.readthedocs.io/en/latest/algo/observations.html#modeling-wifi-and-cell-stations) (our generic term for cell towers, WiFi Access points, and BlueTooth location beacons used for location) is "the area where users see the station". The OSM model is "the physical location of the cell tower", which is subtly different. I think MLS would need to start modeling physical position as well as observation position to be able to collaborate. Similar model changes would be needed to effectively model WiFi router locations.

For privacy reasons, we've stopped associating observations with a particular user, and removed the associated leaderboard (maybe in 2018, a little before my time). This is a big step away from supporting GPS traces, or other tracking IDs as proposed in issue #386. We may revisit these policies in the future.

**Comment by Matthias84** [comment]
Indeed OSM is focused on public visible groundtruth data, which everybody can verify. So wifi positions isn't in focus. But the (estimated) position of cell-towers could be presented as overlay on a QA tool site, or as task in our gamification QA tools as maproulette. To sad, that you don't gather raw GPS tracks, but I see the privacy aspect!

**Comment by jwhitlock** [comment]
MLS does share cell model data, see the [downloads page](https://location.services.mozilla.com/downloads). The format was designed for collaboration with [OpenCellID](https://opencellid.org/#zoom=16&lat=37.77889&lon=-122.41942). You can see how our model of where you can observe the tower interacts with Open Street Maps model of where the tower is.
