### ISSUE TITLE
redo how docs get generated

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#859]
With all the other projects we maintain and have maintained, when we land changes in GitHub, that triggers a webhook and the project documentation gets rebuilt on ReadTheDocs.

With Ichnaea, there's a git submodule in `docs/` with the compiled documentation. In order to update the docs on github.io, one has to compile the docs and then check them into the submodule and push that. It's very manual, has mechanisms I'm not fond of, and is different than all the other projects we (@jwhitlock and I) maintain.

This issue covers changing how docs get generated such that:

1. it doesn't use git submodules
2. docs get built automatically when PRs get merged to master

I have a strong preference for switching to ReadTheDocs.

**Comment by hannosch** [comment]
The setup was required, when we used auto-generated code API docs extracted from docstrings. For that to work all modules had to be importable and that failed with the Cython based module. RTD didn’t allow any kind of additional setup/install code. You could only have a single pip requirements file at the time. We later gave up on those auto-generated docs, so switching back to RTD should work fine.

**Comment by willkg** [comment]
That's good to know--thank you!

**Comment by willkg** [comment]
Docs are correctly building on ReadTheDocs now: https://ichnaea.readthedocs.io/en/latest/

@jwhitlock and I talked about what to do with the github.io docs. I have a couple of ideas:

1. update all the .html files in the gh-pages branch to redirect to ReadTheDocs
2. remove all the .html files in the gh-pages branch and create a single index.html that redirects to ReadTheDocs

I'm inclined to do the first one even though it's a little more arduous.

**Comment by willkg** [comment]
I went through all the html files in gh-pages branch and redid them as redirects.

https://mozilla.github.io/ichnaea/

@jwhitlock pointed out I didn't manage to delete the submodule. He's going to do a PR for that and then we're done here.

**Comment by willkg** [comment]
This is all set now.
