### ISSUE TITLE
Use SQLAlchemy 1.2 / 1.3 features

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#887]
*Note: I intend to add tasks to this issue as I read the SQLAlchemy docs and ichnaea's database code*

*Note 2: I'm done with my first pass, I don't expect to add more tasks.*

Update ichnaea's database code to use SQLAlchemy 1.3 and earlier features rather than custom code:

* [x] Switch from ``check_connection`` to ``create_engine(pool_pre_ping=True)``
* [x] Remove ``PingableSession``, if possible
* [x] Switch from custom ``on_duplicate`` to ``on_duplicate_key_update``
* [x] Change ``sqlalchemny`` logger to ``sqlalchemy``
* [x] Remove old database tests

When using a connection pool, it is possible that a pooled session is disconnected. SQLAlchemy 1.2 implements [pessimistic disconnect handling](https://docs.sqlalchemy.org/en/13/core/pooling.html#disconnect-handling-pessimistic) by adding a parameter ``pool_pre_ping=True`` to ``create_engine``. When a session is checked out of the pool, a light SQL command such as ``SELECT (1);`` is sent, to determine if the session was dropped by the remote database. SQLAlchemy 1.3 improved ``pool_pre_ping`` by using lower-level engine features, rather than SQL, when available. The ``pool_pre_ping`` setting can replace ``ichnaea.db.check_connection``:

https://github.com/mozilla/ichnaea/blob/8ce36efa57c462a896b1b524cd8f956620a460a6/ichnaea/db.py#L222-L228

This may also make ``ichnaea.db.PingableSession`` unnecessary.

**Comment by jwhitlock** [comment]
MySQL supports an "update or insert" or "upsert" syntax, to update a row if the primary key exists and insert a new row if it doesn't. SQLAlchemy 1.2 added support for [INSERT…ON DUPLICATE KEY UPDATE](https://docs.sqlalchemy.org/en/13/dialects/mysql.html#insert-on-duplicate-key-update-upsert). This could replace the custom ``ichnaea.db.on_duplicate`` addition:

https://github.com/mozilla/ichnaea/blob/8ce36efa57c462a896b1b524cd8f956620a460a6/ichnaea/db.py#L51-L61

This is used as ``mysql_on_duplicate`` when inserting values, such as in ``ichnaea.data.stats.StatCounterUpdater``:

https://github.com/mozilla/ichnaea/blob/8ce36efa57c462a896b1b524cd8f956620a460a6/ichnaea/data/stats.py#L67-L71

**Comment by jwhitlock** [comment]
This isn't an upgrade issue, but in ``ichnaea.log`` there is a logging config for ``sqlalchemny``, which I think should be ``sqlalchemy``:

https://github.com/mozilla/ichnaea/blob/8ce36efa57c462a896b1b524cd8f956620a460a6/ichnaea/log.py#L55-L58

**Comment by jwhitlock** [comment]
There are tests in ``ichnaea.tests.test_db.py`` that mention being fixed in PyMySQL 0.6.7, and we're on 0.7.11:

https://github.com/mozilla/ichnaea/blob/8ce36efa57c462a896b1b524cd8f956620a460a6/ichnaea/tests/test_db.py#L26-L31

There may be additional test changes and deletions in this file as other tasks are done.

**Comment by willkg** [comment]
While reviewing, I had to find the migration docs to see all the changes. Copying them here so I don't forget:

* SQLAlchemy 1.2: https://docs.sqlalchemy.org/en/13/changelog/migration_12.html
* SQLAlchemy 1.3: https://docs.sqlalchemy.org/en/13/changelog/migration_13.html
