### ISSUE TITLE
switch everything to use json module

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#888]
Ichnaea uses json in some places and simplejson in others.

This issue covers figuring out whether there's a compelling reason to keep doing that. If there is, we should document why a developer should use simplejson instead of json so there's convention and consistency. If there isn't a reason, then we should switch everything to use one or the other.

**Comment by jwhitlock** [comment]
I support switching ichnaea code to use the standard library ``json``.

From the [simplejson docs](https://simplejson.readthedocs.io/en/latest/):

> `simplejson` exposes an API familiar to users of the standard library `marshal` and `pickle` modules. It is the externally maintained version of the json library contained in Python 2.6, but maintains compatibility with Python 2.5 and (currently) has significant performance advantages, even without using the optional C extension for speedups. `simplejson` is also supported on Python 3.3+.

There's a lot of benchmarks from 2011-2014 showing speed improvements in ``simplejson`` version ``json`` in Python 2.6 and 2.7. All appearances are that these speed improvements were merged into the standard library ``json``. It might be worth a blog article, if you are inclined.

``datadog`` requires ``simplejson`` until 0.24.0 (update issue #867).

**Comment by jwhitlock** [comment]
I started to look into this a little more. Most uses of ``simplejson`` would be easy enough to change. In Python 2, ``json.dumps`` returned a bytestring (type ``str``), and in Python 3, it returns a unicode string.  ``simplejson`` returns a unicode string in both cases, so the code is careful to change to and from utf-8 encoded bytestrings as it passes data to and from Redis.

A slightly harder part is a Celery serialization method ``"internal_json"`` that uses simplejson's functions to handle content encoded in UTF-8:

https://github.com/mozilla/ichnaea/blob/a6a5426413219878e8d32152142beb2a1e2cb89e/ichnaea/taskapp/config.py#L28-L34

This is used in the task app as the result and task serializer:

https://github.com/mozilla/ichnaea/blob/a6a5426413219878e8d32152142beb2a1e2cb89e/ichnaea/taskapp/settings.py#L79-L81

In Celery 3, the default serializer was ``pickle``, and [Celery 4 switchs to ``json``](https://docs.celeryproject.org/en/latest/history/whatsnew-4.0.html#json-is-now-the-default-serializer). We should be able to switch from ``internal_json`` to the built-in ``json``, as part of #861 (lastest celery 3) and then #862 (celery 4).
