### ISSUE TITLE
switch templating language

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#895]
Ichnaea currently uses chameleon for website templates which uses the page templating language. All the other projects we maintain use Jinja2.

This issue covers switching to Jinja2 assuming there aren't compelling reasons to stick with chameleon that override our preferences.

**Comment by jwhitlock** [comment]
The Pyramid docs mention Chameleon, Jinja2, and Mako:

https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/templates.html#available-add-on-template-system-bindings

**Comment by michabotti123456** [comment]
Germany
