### ISSUE TITLE
fix celery configuration

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#913]
There's some configuration being done in `ichnaea/taskapp/settings.py`. In prod, the script sets the `worker_concurrency` to double the number of cores. Seems like that got lost at some point.

This issue covers adding that as an environment variable.

While doing that, we should look at what other things should be configurable.

**Comment by willkg** [comment]
https://docs.celeryproject.org/en/latest/userguide/configuration.html

Also, we probably want to do this after upgrading celery in issue #862 .

**Comment by jwhitlock** [comment]
With celery 4, the logging level is now set on the command line, like ``--loglevel=info``. I find ``info`` useful for ensuring things are working in development, but ``warning`` might be right for production.  Another setting?
