### ISSUE TITLE
Replace repoze.lru with local memory cache

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#919]
``ichnaea/api/key.py`` uses ``repoze.lru.ExpiringLRUCache`` to cache API keys:

https://github.com/mozilla/ichnaea/blob/0dc80caa336e3351c5f6fc825b5caf51536a1be2/ichnaea/api/key.py#L11-L13

[repose.lru](https://github.com/repoze/repoze.lru) was a dependency of Pyramid until 1.10. This dependency has moved to defaults.

An Least-Recently-Used cache may be well-suited for API lookups - often, the requesting key is most recent or one of the most recent keys. However, there are only a handful of keys, so the entire table could be loaded without causing memory pressure.

One alternate would be to re-write the code to use the built-in [functools.lru_cache](https://docs.python.org/3.4/library/functools.html#functools.lru_cache), which is what Pyramid now uses instead of ``repoze.lru``. To get the values to expire, the stored value would need to include the expiration timestamp, and we'd need to exclude the SQLAlchemy session, so it may be an awkward implementation.

Another alternative would be to re-implement the cache (LRU or just expiring) in ichnaea code.

Or, we could decide that ``repoze.lru.ExpiringLRUCache`` is the right tech and we should keep it, even though we no longer have to install it for Pyramid.

**Comment by willkg** [comment]
I wrote an `ExpiringCache` for Socorro. It's used in the `BetaVersionRule` in the processor.

https://github.com/mozilla-services/socorro/blob/master/socorro/lib/cache.py

We could switch to that: it's easy to extract, it has tests, it doesn't add a dependency, and it's been in prod in Socorro for a year.

Does that sound like a viable option?

**Comment by jwhitlock** [comment]
Yes, that would work for me! If we're going to rely on battle-tested code of a narrowly scoped algorithm, I'd rather it be one we maintain, then one that is out of fashion with the current Pyramid maintainers.

**Comment by jwhitlock** [comment]
After some discussion with the services engineering team, there's still a risk relying on https://github.com/repoze/repoze.lru, which hasn't been touched since September 2017. A good first issue may be to replace this code as suggested. I've also considered loading the entire API table into memory at startup, but that is a bigger issue than replacing this dependency.

**Comment by jwhitlock** [comment]
@willkg is thinking of replacing Socorro's ``ExpiringCache`` with [TTLCache](https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache) from [cachetools](https://github.com/tkem/cachetools) ([bug 1669977](https://bugzilla.mozilla.org/show_bug.cgi?id=1669977)). This looks like a drop-in replacement for ``lru.ExpiringLRUCache``, and the project is still under active maintenance.
