### ISSUE TITLE
sort out deprecated API situation

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#922]
There are a bunch of API endpoints, several of which are marked as deprecated.

We should remove the deprecated endpoints. I think we need to do something like this:

1. determine usage of endpoints and by which API keys on MLS
2. remove code, tests, and documentation for endpoints which are no longer used
3. write up an issue for each endpoint that's still in use with the plan to delete it

**Comment by willkg** [comment]
@jwhitlock and I were discussing whether it helps to do this before switching to the new infra or afterwards. I think it helps to do it before since it could reduce the amount of stuff to test, but it shouldn't block the new infrastructure.

Does that make sense? Are there other advantages to making this block the new infrastructure?

**Comment by willkg** [comment]
I looked at the last week of data. Here's the two submit API deprecations:

* `/v1/submit/`: 4.31m
* `/v1/geosubmit/`: 492k

The currently supported submit API endpoint is `/v2/geosubmit/` and either there are 0 instances of that in the last week or there's a bug in gathering metrics and those numbers are showing up somewhere else. I'm guessing the former. I think the stumblers never updated to the `/v2/geosubmit/` API.

* `/v1/search/`: 249k

I don't know what uses search. It was deprecated by `/v1/geolocate/` and that has billions of uses. Seems like we can probably nix search. I'll get a list of API keys to see who's using it.

**Comment by willkg** [comment]
I can't figure out how to figure out `/v1/search` usage, so I sent an email to ckolos who can.

**Comment by willkg** [comment]
The vast majority of `/v1/search/` use is a non-key. There's one other api key that's using it a tiny bit, but it's not clear for what.

I think we're ok to delete `/v1/search/` now.

**Comment by hannosch** [comment]
v1/search without an API key could be old Firefox OS based phones. Some of those based on Mediatek and Spreadtrum based chips were shipped without an API key and no means to update the firmware.

But I think those can safely be ignored nowadays. I don’t remember any other legitimate use cases.

**Comment by willkg** [comment]
I don't think we can get any further with this for now. I'm going to bump it out of the "new infra" milestone.

**Comment by jwhitlock** [comment]
The biggest user of ``/v1/submit/`` API is the Fennec codebase of Firefox for Android. This is being replaced by the Fenix codebase, which does not have a built-in stumbler, so the use of this API will decline.

The biggest user of the ``/v1/geosubmit/`` API is [MozStumbler](https://github.com/mozilla/mozstumbler). It has a bug under Android 10, and we haven't identified an Android developer to fix, test, and release a new version.

In both cases, it is not a huge burden to continue supporting the old APIs. New users like [TowerCollector](https://github.com/zamojski/TowerCollector) have adopted the current API.

I'm closing this for now. We can revisit if we get a chance to update FF for Android or MozStumbler.
