### ISSUE TITLE
location.services.mozilla.com has failed the web security baseline

### ISSUE THREAD

**Issue by mozcloudsec** [mozilla/ichnaea#970]
Site https://location.services.mozilla.com has failed the web security baseline scan.

The failing tests are:

 X-Content-Type-Options Header Missing [10021] x 17 
 * https://location.services.mozilla.com/robots.txt (200 OK)
 * https://location.services.mozilla.com/__heartbeat__ (200 OK)
 * https://location.services.mozilla.com/__lbheartbeat__ (200 OK)
 * https://location.services.mozilla.com/__version__ (200 OK)
 * https://location.services.mozilla.com/static/images/favicon.png (200 OK)

 Cross-Domain Misconfiguration [10098] x 3 
 * https://location.services.mozilla.com/__heartbeat__ (200 OK)
 * https://location.services.mozilla.com/__lbheartbeat__ (200 OK)
 * https://location.services.mozilla.com/__version__ (200 OK)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=location.services.mozilla.com) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by moz-hwine** [comment]
The following test(s) for site https://location.services.mozilla.com have now passed:

 * X-Content-Type-Options Header Missing

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline scan for site https://location.services.mozilla.com now passes - well done team!
