### ISSUE TITLE
update module owners

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#975]
The module owners for MLS list @hannosch as owner and @crankycoder and @graydon as peer emeritus.

https://wiki.mozilla.org/Modules/Other#Mozilla_Location_Service_.28MLS.29

Currently, @jwhitlock and I are engineers on the project and @ckolos is ops. We've been making some compliance changes, updating the software to current versions of things, and making changes to support an infrastructure migration to get us back to current conventions. Additionally, there are some changes coming up in 2020.

This is currently an active project. We should update the module owners and peers.

After talking with @jwhitlock, @ckolos, and @lonnen, we agreed I should step up as module owner with @jwhitlock as a peer.

@hannosch: Is it ok to make those changes and move you to owner emeritus?

**Comment by hannosch** [comment]
+1 as detailed via email :-)

**Comment by willkg** [comment]
@hannosch Thank you!

I sent an email to the governance list to update the module information. Unless there are objections, I'll update the wiki in a week.

**Comment by willkg** [comment]
I have updated the module owners information and sent a followup email to the governance list. All done here!
