### ISSUE TITLE
sentry issues should be tagged with node type

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#988]
Sentry issues should be tagged with the node type. For example, issues coming from the webapp should have "node: webapp" in the metadata so that we can see the breakdown of node types in the Sentry issue.

**Comment by djmitche** [comment]
I can take a look at this -- we do something similar in Taskcluster.

**Comment by djmitche** [comment]
[Here's](https://github.com/taskcluster/taskcluster/blob/eff2fb532fe476d5c4c881eb39fa9be865cd5b02/libraries/monitor/src/plugins/sentry.js#L15-L26) how we do this in Taskcluster:

```javscript
  constructor({ dsn, taskclusterVersion, serviceName, processName }) {
    if (!dsn) {
      throw new Error('SentryReporter plugin must have a `dsn` set to work.');
    }   
    Sentry.init({
      dsn,
      release: taskclusterVersion,
    }); 
    Sentry.configureScope(scope => {
      scope.setTag('service', serviceName);
      scope.setTag('proc', processName);
    }); 
  }
```

**Comment by djmitche** [comment]
https://github.com/mozilla/ichnaea/pull/1320
