### ISSUE TITLE
Clarify documentation / comments for UMTS stations

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#989]
It is confusing when looking at the code, the code comments, and the API documentation what to do for UMTS cell stations.  My guess is that the example in ``cell.py`` is incorrect, and the API documentation is correct. More research is needed to determine if the database has (duplicate?) records for both radio types.

The code comment for WCDMA says that ``wcdma`` is the radio type for  `UMTS`, `HSPA`, `HSDPA`, `HSPA+` and `HSUPA`. However, the example shows "umts" for the radio type:

https://github.com/mozilla/ichnaea/blob/4b7aa181ddd708c3f0ab9fa6031c49a707d07d69/ichnaea/models/cell.py#L72-L85

They are distinct types in the constants file, which define the allowed values in the database.

https://github.com/mozilla/ichnaea/blob/4b7aa181ddd708c3f0ab9fa6031c49a707d07d69/ichnaea/models/constants.py#L14-L21

There is code that translated `umts` to `wcdma` when submitted to the API:

https://github.com/mozilla/ichnaea/blob/4b7aa181ddd708c3f0ab9fa6031c49a707d07d69/ichnaea/api/submit/schema.py#L128-L129

The name for this cell type evolved over time:
* [``v1/submit`` API](https://ichnaea.readthedocs.io/en/latest/api/submit.html#cell-fields) - Use `umts`.
* [ ``v1/geosubmit`` API](https://ichnaea.readthedocs.io/en/latest/api/geosubmit.html) - Not specified, same as ``v1/submit``?
* [ ``v2/geosubmit`` API](https://ichnaea.readthedocs.io/en/latest/api/geosubmit2.html#cell-tower-fields) - Use `wcdma`

**Comment by hannosch** [comment]
For v1/geosubmit, there’s an easily overlooked sentence in there:

> The cell record has been extended over the geolocate schema to include three more optional fields

And v1/geolocate specifies wcdma.

Basically submit and search used the term umts. Then we defined the new APIs to mirror or extend the Google defined APIs and those used the term wcdma. Internally in the data pipeline we never really moved away from the original submit schema. So it’s a bit of a dance to convert things back and forth. In the end we use umts and wcdma to mean the same thing. That’s why the constants file defines both as an alias for the same constant.

**Comment by jwhitlock** [comment]
Thanks @hannosch, that helps.

I tried to find a way to improve the `/v1/geosubmit` docs by linking to the [/v1/geolocate](https://ichnaea.readthedocs.io/en/latest/api/geolocate.html) docs, but it didn't make much sense to me as I was doing it. For example, the `v1/geosubmit` doc says it added the fields `age`, `asu` and `psc`, but `age` and `psc` are already defined on `/v1/geolocate`, and `asu` sounds a lot like `signalStrength`. I decided to leave a deprecated API doc alone, rather than dig into the schemas.

That leaves changing `ichnaea/models/cell.py` as the only action to resolve this issue.

**Comment by jwhitlock** [comment]
When re-reading this bug, this sentance seemed to require an answer:

> More research is needed to determine if the database has (duplicate?) records for both radio types.

The cell radio types are in this code:

https://github.com/mozilla/ichnaea/blob/4b7aa181ddd708c3f0ab9fa6031c49a707d07d69/ichnaea/models/constants.py#L14-L21

When writing the bug, I missed that both `wcdma` and `umts` are set to `2`, which means they are synonyms for the same database value of `2`.

I think a way to make this clearer is to assign on the same line:

```python
    wcdma = umts = 2  # wcdma is preferred; umts is the original, deprecated name
```
